/* Jigger 데이터: 칵테일 · 주류 상식 · 안주 레시피
   메인 페이지(index.html)와 검색용 페이지를 만드는 scripts/build.mjs가 함께 읽어요.
   칵테일이나 안주를 추가·수정할 때는 이 파일을 고치면 돼요. */
window.JIGGER_DATA = (function(){
'use strict';

/* 검색에서 자주 쓰는 다른 표기 (조주기능사 시험 표기는 EXAM의 ko로 따로 검색돼요) */
const ALIAS = {
  mojito:['모히또'], margarita:['마르가리타'], 'pina-colada':['피나콜라다','피나 콜라다'], 'gin-tonic':['진토닉'],
  'moscow-mule':['모스코뮬'], 'dark-n-stormy':['다크앤스토미'], 'tom-collins':['톰콜린스'],
  'tequila-sunrise':['데킬라 선라이즈'], 'whiskey-sour':['위스키사워'],
  'singapore-sling':['싱가폴 슬링'], 'blue-hawaiian':['블루 하와이안'], seabreeze:['씨브리즈'], 'pousse-cafe':['푸즈카페','푸스 카페'], 'mai-tai':['마이 타이'],
  apricot:['애프리코트'], 'long-island-iced-tea':['롱 아일랜드 아이스티'], 'june-bug':['준벅'],
  cosmopolitan:['코즈모폴리턴'], sidecar:['사이드 카'], negroni:['니그로니']
};

/* ---------- 데이터 ---------- */
const C = {
  gin:'#b7d3ce', vodka:'#c5d5e3', rum:'#dad9bd', dkrum:'#7a3f1a', tequila:'#dcd39b', whisky:'#c07a2b', cognac:'#b8621f',
  dryv:'#e4dc9c', sweetv:'#7d2a24', campari:'#c4202f', aperol:'#f2662b', cointreau:'#f2b962', coffeeliq:'#3b2319', espresso:'#2b1a12',
  lime:'#bfd85a', lemon:'#f0e070', syrup:'#e8dcc0', soda:'#cde4ee', tonic:'#d3e7ec', gingerbeer:'#e2c25f', gingerale:'#e6c75a',
  cranberry:'#c72c4c', pineapple:'#f1cd47', orange:'#f5992a', coconut:'#f4efe2', grenadine:'#c4142c', tomato:'#c73a25',
  prosecco:'#f0e2a0', grapefruit:'#f0a49a', tea:'#a4622a', sparkling:'#f0e2a0'
};
const BASES = ['진','럼','위스키','보드카','테킬라','브랜디','와인·리큐르','우리술','논알콜'];
const BASE_EN = {'진':'Gin','럼':'Rum','위스키':'Whiskey','보드카':'Vodka','테킬라':'Tequila','브랜디':'Brandy','와인·리큐르':'Wine & Liqueur','우리술':'Korean Spirits','논알콜':'Zero Proof'};
const FLAVORS = ['상큼','달콤','쌉쌀','청량','부드러운','스트롱','감칠맛'];
const DIFF = ['쉬움','보통','어려움'];

const GLASS = {
  martini:{name:'칵테일 글라스', d:'M6 10H74L40 62Z', level:20, bottom:62, extra:'M40 62V108M24 110H56'},
  coupe:{name:'쿠페 글라스', d:'M6 26H74C74 48 58 62 40 62C22 62 6 48 6 26Z', level:33, bottom:62, extra:'M40 62V106M24 108H56'},
  rocks:{name:'올드 패션드 글라스', d:'M12 40H68L64 104Q64 108 60 108H20Q16 108 16 104Z', level:54, bottom:108, extra:'',
    ice:[[22,52,15,-8],[40,60,15,10],[27,78,15,6]]},
  highball:{name:'하이볼 글라스', d:'M22 14H58L55 108Q55 112 51 112H29Q25 112 25 108Z', level:30, bottom:112, extra:'',
    ice:[[29,34,15,-6],[34,54,15,8],[28,76,15,-4],[33,94,14,5]]},
  flute:{name:'플루트 글라스', d:'M28 10H52L50 74Q50 82 40 84Q30 82 30 74Z', level:22, bottom:84, extra:'M40 84V108M26 110H54'},
  mug:{name:'코퍼 머그', d:'M14 26H58V100Q58 106 52 106H20Q14 106 14 100Z', level:38, bottom:106, extra:'M58 40H68Q76 40 76 50V68Q76 78 68 78H58',
    ice:[[22,42,15,-6],[35,60,15,8],[24,80,15,4]]},
  wine:{name:'와인 글라스', d:'M20 12H60C60 42 54 58 40 58C26 58 20 42 20 12Z', level:26, bottom:58, extra:'M40 58V106M24 108H56',
    ice:[[28,30,11,-8],[38,40,10,10]]},
  collins:{name:'콜린스 글라스', d:'M24 6H56L54 110Q54 114 50 114H30Q26 114 26 110Z', level:24, bottom:114, extra:'',
    ice:[[30,30,15,-6],[35,50,15,8],[29,70,15,-4],[34,90,14,5]]},
  pilsner:{name:'풋티드 필스너 글라스', d:'M22 8H58L50 76Q48 84 40 84Q32 84 30 76Z', level:22, bottom:84, extra:'M40 84V104M26 106H54',
    ice:[[29,28,13,-6],[37,46,13,8],[31,62,12,-4]]},
  sour:{name:'사워 글라스', d:'M22 30H58L52 64Q49 70 40 70Q31 70 28 64Z', level:38, bottom:70, extra:'M40 70V104M26 106H54'},
  sherry:{name:'셰리 글라스', d:'M28 40H52L48 72Q46 78 40 78Q34 78 32 72Z', level:46, bottom:78, extra:'M40 78V104M28 106H52'},
  liqueur:{name:'리큐르 글라스', d:'M31 52H49L46 72Q45 76 40 76Q35 76 34 72Z', level:56, bottom:76, extra:'M40 76V104M29 106H51'},
  hurricane:{name:'허리케인 글라스', d:'M24 10H56C56 28 68 38 68 58C68 74 54 82 46 86H34C26 82 12 74 12 58C12 38 24 28 24 10Z', level:24, bottom:86, extra:'M40 86V104M26 106H54'}
};

const RECIPES = [
/* ---- 진 ---- */
{id:'martini', ko:'마티니', en:'Dry Martini', base:'진', flav:['스트롱'], abv:28, glass:'martini', liquid:'#d3e6e3', method:'스터', diff:2,
 ing:[['진',60,'ml',C.gin],['드라이 베르무트',10,'ml',C.dryv]],
 steps:['믹싱 글라스에 얼음을 가득 채우고 진과 드라이 베르무트를 넣어요.','바 스푼으로 30초쯤 저어 충분히 차갑게 식혀요.','미리 얼려 둔 칵테일 글라스에 걸러 따라요.','레몬 껍질을 비틀어 향을 입히고 잔에 올려요.'],
 garnish:'레몬 필 또는 올리브', note:'얼음물에 희석되는 정도까지 계산에 넣는 칵테일이에요. 흔들지 않고 저어야 맑고 묵직한 질감이 살아요.'},
{id:'negroni', ko:'네그로니', en:'Negroni', base:'진', flav:['쌉쌀','스트롱'], abv:22, glass:'rocks', liquid:'#b8232e', method:'빌드', diff:1, ice:true,
 ing:[['진',30,'ml',C.gin],['캄파리',30,'ml',C.campari],['스위트 베르무트',30,'ml',C.sweetv]],
 steps:['올드 패션드 글라스에 큰 얼음을 넣어요.','진, 캄파리, 스위트 베르무트를 같은 양으로 넣어요.','바 스푼으로 10~15회 가볍게 저어요.','오렌지 껍질을 비틀어 향을 입히고 올려요.'],
 garnish:'오렌지 필', note:'1:1:1 비율만 지키면 실패하기 어려운 칵테일이에요. 1919년 피렌체에서 네그로니 백작이 주문한 데서 유래했다고 전해져요.'},
{id:'gin-tonic', ko:'진 토닉', en:'Gin & Tonic', base:'진', flav:['청량','쌉쌀'], abv:12, glass:'highball', liquid:'#dcecf0', method:'빌드', diff:1, ice:true,
 ing:[['진',50,'ml',C.gin],['토닉워터',100,'ml',C.tonic]],
 steps:['하이볼 글라스에 얼음을 가득 채워요.','진을 붓고 차갑게 식힌 토닉워터를 잔 벽을 따라 부어요.','바 스푼으로 아래에서 위로 한 번만 저어요.','라임 웨지를 짜 넣고 올려요.'],
 garnish:'라임 웨지', note:'토닉워터는 새로 딴 차가운 병을 쓰는 게 탄산이 오래 가요. 토닉을 세게 저으면 김이 빠져요.'},
{id:'tom-collins', ko:'톰 콜린스', en:'Tom Collins', base:'진', flav:['상큼','청량'], abv:12, glass:'collins', liquid:'#eeeec4', method:'빌드', diff:1, ice:true,
 ing:[['진',50,'ml',C.gin],['레몬주스',25,'ml',C.lemon],['심플 시럽',15,'ml',C.syrup],['소다수',60,'ml',C.soda]],
 steps:['콜린스 글라스에 진, 레몬주스, 심플 시럽을 넣어요.','얼음을 채우고 잘 저어요.','소다수를 잔 끝까지 채우고 가볍게 저어요.','레몬 슬라이스와 체리를 올려요.'],
 garnish:'레몬 슬라이스, 체리', note:'진 사워에 소다수를 더한 형태예요. 레몬을 생과로 짜면 맛 차이가 확실히 나요.'},
{id:'gimlet', ko:'김렛', en:'Gimlet', base:'진', flav:['상큼'], abv:17, glass:'coupe', liquid:'#dfe8b0', method:'셰이크', diff:1,
 ing:[['진',50,'ml',C.gin],['라임주스',25,'ml',C.lime],['심플 시럽',15,'ml',C.syrup]],
 steps:['셰이커에 얼음과 모든 재료를 넣어요.','10~12초 강하게 흔들어요.','차갑게 식힌 쿠페 글라스에 걸러 따라요.','라임 휠을 올려요.'],
 garnish:'라임 휠', note:'전통 레시피는 라임 코디얼을 쓰지만, 생라임과 시럽으로도 충분히 깔끔하게 만들 수 있어요.'},

{id:'singapore-sling', ko:'싱가포르 슬링', en:'Singapore Sling', base:'진', flav:['상큼','청량','달콤'], abv:11, glass:'pilsner', liquid:'#f2a0a0', method:'셰이크 · 빌드', diff:2, ice:true,
 ing:[['진',45,'ml','#b7d3ce'],['레몬주스',15,'ml','#f0e070'],['슈거 파우더',1,'tsp',null],['소다수',90,'ml','#cde4ee'],['체리 브랜디',15,'ml','#8f1d2c']],
 steps:['셰이커에 얼음과 진, 레몬주스, 슈거 파우더를 넣고 흔들어요.','얼음을 채운 풋티드 필스너 글라스에 걸러 따라요.','소다수를 잔 가까이 채워요.','체리 브랜디를 위에 살짝 띄우고 오렌지 슬라이스와 체리로 장식해요.'],
 garnish:'오렌지 슬라이스, 체리', note:'싱가포르 래플스 호텔에서 탄생한 진 칵테일이에요. 흔들어 따른 뒤 소다수를 채우고, 체리 브랜디를 마지막에 위에 올리는 순서를 기억하세요.'},
{id:'gin-fizz', ko:'진 피즈', en:'Gin Fizz', base:'진', flav:['상큼','청량'], abv:10, glass:'highball', liquid:'#eef3e0', method:'셰이크 · 빌드', diff:2, ice:true,
 ing:[['진',45,'ml','#b7d3ce'],['레몬주스',15,'ml','#f0e070'],['슈거 파우더',1,'tsp',null],['소다수',90,'ml','#cde4ee']],
 steps:['셰이커에 얼음과 진, 레몬주스, 슈거 파우더를 넣고 흔들어요.','얼음을 채운 하이볼 글라스에 걸러 따라요.','소다수를 가득 채우고 가볍게 저어요.','레몬 슬라이스로 장식해요.'],
 garnish:'레몬 슬라이스', note:'진 사워에 소다수를 더한 클래식 피즈예요. 톰 콜린스와 재료가 비슷하지만 셰이커로 먼저 흔든다는 점이 달라요.'},
/* ---- 럼 ---- */
{id:'mojito', ko:'모히토', en:'Mojito', base:'럼', flav:['상큼','청량'], abv:10, glass:'highball', liquid:'#d6e8ac', method:'빌드', diff:2, ice:true,
 ing:[['화이트 럼',40,'ml',C.rum],['라임주스',30,'ml',C.lime],['심플 시럽',15,'ml',C.syrup],['민트 잎',8,'잎','#5aa469'],['소다수',60,'ml',C.soda]],
 steps:['하이볼 글라스에 라임주스, 시럽, 민트 잎을 넣고 향이 올라올 만큼만 가볍게 눌러요. 세게 으깨면 쓴맛이 나요.','럼을 붓고 잘게 부순 얼음을 가득 채워요.','바 스푼으로 아래에서 위로 저어 섞어요.','소다수를 채우고 민트 가지를 올려요.'],
 garnish:'민트 가지, 라임 웨지', note:'쿠바 하바나에서 사랑받은 칵테일이에요. 민트는 손바닥에 톡 쳐서 올리면 향이 더 살아나요.'},
{id:'daiquiri', ko:'다이키리', en:'Daiquiri', base:'럼', flav:['상큼'], abv:18, glass:'coupe', liquid:'#eef0c8', method:'셰이크', diff:1,
 ing:[['화이트 럼',45,'ml',C.rum],['라임주스',25,'ml',C.lime],['심플 시럽',10,'ml',C.syrup]],
 steps:['셰이커에 얼음과 모든 재료를 넣어요.','10~12초 강하게 흔들어요.','차갑게 식힌 쿠페 글라스에 걸러 따라요.','라임 휠을 잔 가장자리에 걸어요.'],
 garnish:'라임 휠', note:'럼, 라임, 설탕 세 가지로 이루어진 단순한 구성이라 바텐더의 기본기를 볼 때 자주 쓰여요.'},
{id:'pina-colada', ko:'피냐 콜라다', en:'Piña Colada', base:'럼', flav:['달콤','부드러운'], abv:10, glass:'hurricane', liquid:'#f4ecd0', method:'블렌드', diff:2,
 ing:[['화이트 럼',50,'ml',C.rum],['코코넛 크림',50,'ml',C.coconut],['파인애플 주스',50,'ml',C.pineapple]],
 steps:['블렌더에 럼, 코코넛 크림, 파인애플 주스를 넣어요.','얼음 한 컵(약 150 g)을 넣고 곱게 갈아요.','허리케인 글라스에 따라요.','파인애플 웨지과 체리로 장식해요.'],
 garnish:'파인애플 웨지, 체리', note:'푸에르토리코를 대표하는 칵테일이에요. 얼음은 재료 비율에서 제외했어요.'},
{id:'dark-n-stormy', ko:'다크 앤 스토미', en:"Dark 'n' Stormy", base:'럼', flav:['청량','상큼'], abv:12, glass:'highball', liquid:'#7a3f1a', liquid2:'#d9b552', method:'빌드', diff:1, ice:true,
 ing:[['다크 럼',50,'ml',C.dkrum],['진저비어',100,'ml',C.gingerbeer],['라임주스',10,'ml',C.lime]],
 steps:['하이볼 글라스에 얼음을 채우고 라임주스와 진저비어를 넣어요.','다크 럼을 숟가락 뒷면을 타고 천천히 부어 위에 띄워요.','라임 웨지를 올려요.'],
 garnish:'라임 웨지', note:'폭풍우 치는 구름 같은 층이 이름의 유래예요. 버뮤다에서 시작된 칵테일로 알려져 있어요.'},

{id:'bacardi', ko:'바카디', en:'Bacardi Cocktail', base:'럼', flav:['상큼'], abv:21, glass:'martini', liquid:'#f2a3a8', method:'셰이크', diff:2,
 ing:[['바카디 화이트 럼',52.5,'ml','#dad9bd'],['라임주스',22.5,'ml','#bfd85a'],['그레나딘 시럽',1,'tsp',null]],
 steps:['셰이커에 얼음과 바카디 화이트 럼, 라임주스, 그레나딘 시럽을 넣어요.','10초쯤 세게 흔들어요.','차갑게 식힌 칵테일 글라스에 걸러 따라요.'],
 garnish:'없음', note:'다이키리의 설탕 대신 그레나딘을 넣은 분홍빛 칵테일이에요. 이름 그대로 바카디 럼을 쓰는 것이 원칙이에요.'},
{id:'cuba-libre', ko:'쿠바 리브레', en:'Cuba Libre', base:'럼', flav:['청량','달콤'], abv:11, glass:'highball', liquid:'#4a2414', method:'빌드', diff:1, ice:true,
 ing:[['라이트 럼',45,'ml','#dad9bd'],['라임주스',15,'ml','#bfd85a'],['콜라',90,'ml','#3a1c10']],
 steps:['하이볼 글라스에 얼음을 채워요.','라이트 럼과 라임주스를 넣어요.','콜라를 가득 채우고 가볍게 저어요.','레몬 웨지로 장식해요.'],
 garnish:'레몬 웨지', note:'"자유 쿠바"라는 뜻의 럼 앤 콜라예요. 실기 표준 장식은 라임이 아니라 레몬 웨지예요.'},
{id:'blue-hawaiian', ko:'블루 하와이언', en:'Blue Hawaiian', base:'럼', flav:['달콤','청량'], abv:11, glass:'pilsner', liquid:'#3a9ad9', method:'블렌드', diff:2, ice:true,
 ing:[['라이트 럼',30,'ml','#dad9bd'],['블루 큐라소',30,'ml','#2a7fd1'],['코코넛 럼',30,'ml','#f4efe2'],['파인애플 주스',75,'ml','#f1cd47']],
 steps:['블렌더에 잘게 부순 얼음과 모든 재료를 넣어요.','부드러워질 때까지 갈아요.','풋티드 필스너 글라스에 따라요.','파인애플 웨지와 체리로 장식해요.'],
 garnish:'파인애플 웨지, 체리', note:'블루 큐라소로 바다색을 낸 트로피컬 칵테일이에요. 코코넛 럼의 부드러운 단맛이 파인애플과 잘 어울려요.'},
{id:'mai-tai', ko:'마이타이', en:'Mai-Tai', base:'럼', flav:['달콤','상큼'], abv:10, glass:'pilsner', liquid:'#f0a040', method:'블렌드', diff:2, ice:true,
 ing:[['라이트 럼',37.5,'ml','#dad9bd'],['트리플 섹',22.5,'ml','#f2b962'],['라임주스',30,'ml','#bfd85a'],['파인애플 주스',30,'ml','#f1cd47'],['오렌지 주스',30,'ml','#f5992a'],['그레나딘 시럽',7.5,'ml','#c4142c']],
 steps:['블렌더에 잘게 부순 얼음과 모든 재료를 넣어요.','부드러워질 때까지 갈아요.','풋티드 필스너 글라스에 따라요.','파인애플(또는 오렌지) 웨지와 체리로 장식해요.'],
 garnish:'파인애플(또는 오렌지) 웨지, 체리', note:'타히티어로 "최고"라는 뜻의 트로피컬 칵테일이에요. 실기에서는 블렌더로 만들어요.'},
/* ---- 위스키 ---- */
{id:'old-fashioned', ko:'올드 패션드', en:'Old Fashioned', base:'위스키', flav:['스트롱','쌉쌀'], abv:27, glass:'rocks', liquid:'#b8651b', method:'빌드', diff:2, ice:true,
 ing:[['버번 위스키',45,'ml',C.whisky],['각설탕',1,'개','#f1ead8'],['앙고스투라 비터스',2,'dash',null],['물','몇 방울','',null]],
 steps:['올드 패션드 글라스에 각설탕과 앙고스투라 비터스를 넣고 물을 몇 방울 떨어뜨려요.','설탕이 녹을 때까지 으깨며 저어요.','버번을 붓고 큰 얼음을 넣어요.','바 스푼으로 20~30초 저어 차갑게 만들어요.','오렌지 껍질로 향을 입히고 올려요.'],
 garnish:'오렌지 필', note:'설탕, 비터스, 물, 위스키. 칵테일의 원형에 가깝다고 이야기되는 가장 오래된 레시피 중 하나예요.'},
{id:'manhattan', ko:'맨해튼', en:'Manhattan', base:'위스키', flav:['스트롱','달콤'], abv:28, glass:'coupe', liquid:'#8b2a1e', method:'스터', diff:2,
 ing:[['라이 위스키',50,'ml',C.whisky],['스위트 베르무트',20,'ml',C.sweetv],['앙고스투라 비터스',1,'dash',null]],
 steps:['믹싱 글라스에 얼음과 모든 재료를 넣어요.','30초 정도 저어 차갑게 만들어요.','차갑게 식힌 쿠페 글라스에 걸러 따라요.','체리를 올려요.'],
 garnish:'체리', note:'라이 위스키의 매콤함과 베르무트의 달콤함이 균형을 이뤄요. 라이가 없으면 버번으로 대체해도 좋아요.'},
{id:'whiskey-sour', ko:'위스키 사워', en:'Whiskey Sour', base:'위스키', flav:['상큼','달콤'], abv:17, glass:'rocks', liquid:'#eab558', method:'셰이크', diff:1, ice:true,
 ing:[['버번 위스키',45,'ml',C.whisky],['레몬주스',25,'ml',C.lemon],['심플 시럽',20,'ml',C.syrup]],
 steps:['셰이커에 얼음과 모든 재료를 넣어요.','10~12초 강하게 흔들어요.','얼음을 채운 올드 패션드 글라스에 걸러 따라요.','오렌지 슬라이스와 체리를 올려요.'],
 garnish:'오렌지 슬라이스, 체리', note:'부드러운 거품을 원하면 계란 흰자 한 개를 더해 먼저 얼음 없이 한 번 흔든 뒤 다시 흔들어 보세요.'},
{id:'mint-julep', ko:'민트 줄렙', en:'Mint Julep', base:'위스키', flav:['청량','스트롱'], abv:25, glass:'rocks', liquid:'#d9d6a0', method:'빌드', diff:2, ice:true,
 ing:[['버번 위스키',60,'ml',C.whisky],['심플 시럽',10,'ml',C.syrup],['민트 잎',8,'잎','#5aa469']],
 steps:['올드 패션드 글라스에 시럽과 민트 잎을 넣고 살살 눌러요.','버번을 붓고 부순 얼음을 반쯤 채워요.','잔 표면에 서리가 낄 때까지 저어요.','부순 얼음을 봉긋하게 더 얹고 민트 가지로 장식해요.'],
 garnish:'민트 가지 한 다발', note:'미국 켄터키 더비의 공식 음료로 유명해요. 얼음을 곱게 부술수록 차갑게 즐길 수 있어요.'},

{id:'new-york', ko:'뉴욕', en:'New York', base:'위스키', flav:['상큼','스트롱'], abv:21, glass:'martini', liquid:'#d9703a', method:'셰이크', diff:2,
 ing:[['버번 위스키',45,'ml','#c07a2b'],['라임주스',15,'ml','#bfd85a'],['슈거 파우더',1,'tsp',null],['그레나딘 시럽',0.5,'tsp',null]],
 steps:['셰이커에 얼음과 모든 재료를 넣어요.','10초쯤 세게 흔들어요.','차갑게 식힌 칵테일 글라스에 걸러 따라요.','레몬 껍질을 비틀어 향을 입히고 올려요.'],
 garnish:'레몬 필', note:'버번에 라임과 그레나딘을 더해 노을처럼 붉은 빛이 도는 칵테일이에요. 레몬이 아니라 라임주스가 들어가는 점을 헷갈리지 마세요.'},
{id:'boulevardier', ko:'불바디에', en:'Boulevardier', base:'위스키', flav:['쌉쌀','스트롱'], abv:23, glass:'rocks', liquid:'#8e2a22', method:'스터', diff:2, ice:true,
 ing:[['버번 위스키',30,'ml','#c07a2b'],['스위트 베르무트',30,'ml','#7d2a24'],['캄파리',30,'ml','#c4202f']],
 steps:['믹싱 글라스에 얼음과 버번 위스키, 스위트 베르무트, 캄파리를 넣어요.','바 스푼으로 20초쯤 저어 차갑게 식혀요.','얼음을 넣은 올드 패션드 글라스에 걸러 따라요.','오렌지 껍질을 비틀어 향을 입히고 올려요.'],
 garnish:'오렌지 필', note:'네그로니의 진을 버번으로 바꾼 칵테일로, 2024년 실기 목록에 새로 추가됐어요. 네그로니와 달리 스터 기법이고 오렌지 껍질로 장식해요.'},
{id:'rusty-nail', ko:'러스티 네일', en:'Rusty Nail', base:'위스키', flav:['달콤','스트롱'], abv:36, glass:'rocks', liquid:'#b86a24', method:'빌드', diff:1, ice:true,
 ing:[['스카치 위스키',30,'ml','#c98a3a'],['드람뷔',15,'ml','#c4822e']],
 steps:['올드 패션드 글라스에 얼음을 넣어요.','스카치 위스키와 드람뷔를 넣어요.','바 스푼으로 가볍게 저어요.'],
 garnish:'없음', note:'스카치 위스키에 꿀과 허브 향의 드람뷔를 더한 칵테일이에요. 식후에 천천히 마시기 좋아요.'},
/* ---- 보드카 ---- */
{id:'moscow-mule', ko:'모스코 뮬', en:'Moscow Mule', base:'보드카', flav:['청량','상큼'], abv:9, glass:'mug', liquid:'#e6cc70', method:'빌드', diff:1, ice:true,
 ing:[['보드카',45,'ml',C.vodka],['라임주스',15,'ml',C.lime],['진저비어',120,'ml',C.gingerbeer]],
 steps:['코퍼 머그에 얼음을 가득 채워요.','보드카와 라임주스를 넣어요.','진저비어를 채워 가볍게 저어요.','라임 웨지와 민트 가지를 올려요.'],
 garnish:'라임 웨지, 민트 가지', note:'구리 머그는 차가운 온도를 오래 유지해 줘요. 없으면 하이볼 글라스로도 충분해요.'},
{id:'cosmopolitan', ko:'코스모폴리탄', en:'Cosmopolitan', base:'보드카', flav:['상큼','달콤'], abv:18, glass:'martini', liquid:'#e0507a', method:'셰이크', diff:2,
 ing:[['보드카',40,'ml',C.vodka],['쿠앵트로',15,'ml',C.cointreau],['크랜베리 주스',30,'ml',C.cranberry],['라임주스',15,'ml',C.lime]],
 steps:['셰이커에 얼음과 모든 재료를 넣어요.','10초 흔들어 차갑게 만들어요.','차가운 칵테일 글라스에 걸러 따라요.','오렌지 껍질로 향을 입히고 장식해요.'],
 garnish:'오렌지 필', note:'크랜베리 주스는 무가당을 쓰면 더 산뜻하고, 가당이면 달콤하게 돼요. 취향에 맞춰 골라 보세요.'},
{id:'espresso-martini', ko:'에스프레소 마티니', en:'Espresso Martini', base:'보드카', flav:['쌉쌀','달콤'], abv:17, glass:'martini', liquid:'#b58a5a', liquid2:'#2a1a12', method:'셰이크', diff:2,
 ing:[['보드카',50,'ml',C.vodka],['커피 리큐르',10,'ml',C.coffeeliq],['심플 시럽',10,'ml',C.syrup],['에스프레소',30,'ml',C.espresso]],
 steps:['에스프레소를 뽑아 식혀 두어요. 뜨거우면 얼음이 너무 녹아요.','셰이커에 얼음과 모든 재료를 넣어요.','15초 이상 아주 강하게 흔들어 고운 거품을 만들어요.','차가운 칵테일 글라스에 걸러 따르고 커피콩 3알을 올려요.'],
 garnish:'커피콩 3알', note:'윗부분의 갈색 크레마가 이 칵테일의 얼굴이에요. 세게, 오래 흔들수록 거품이 촘촘해져요.'},
{id:'bloody-mary', ko:'블러디 메리', en:'Bloody Mary', base:'보드카', flav:['감칠맛'], abv:10, glass:'highball', liquid:'#c0331f', method:'빌드', diff:1, ice:true,
 ing:[['보드카',45,'ml',C.vodka],['토마토 주스',90,'ml',C.tomato],['레몬주스',15,'ml',C.lemon],['우스터 소스',2,'dash',null],['타바스코',2,'dash',null],['소금·후추','한 꼬집','',null]],
 steps:['하이볼 글라스에 얼음을 채워요.','보드카, 토마토 주스, 레몬주스를 넣어요.','우스터 소스, 타바스코, 소금, 후추를 더해요.','바 스푼으로 아래에서 위로 부드럽게 저어요.','셀러리 스틱과 레몬 웨지로 장식해요.'],
 garnish:'셀러리 스틱, 레몬 웨지', note:'짭짤하고 매콤한 맛이라 브런치나 해장 칵테일로 자주 언급돼요. 타바스코는 조금씩 추가하며 맞추세요.'},

{id:'black-russian', ko:'블랙 러시안', en:'Black Russian', base:'보드카', flav:['달콤','스트롱'], abv:30, glass:'rocks', liquid:'#2e1a12', method:'빌드', diff:1, ice:true,
 ing:[['보드카',30,'ml','#c5d5e3'],['커피 리큐르',15,'ml','#3b2319']],
 steps:['올드 패션드 글라스에 얼음을 넣어요.','보드카와 커피 리큐르를 넣어요.','바 스푼으로 가볍게 저어요.'],
 garnish:'없음', note:'보드카에 커피 리큐르를 더한 간단한 칵테일이에요. 위에 크림을 띄우면 화이트 러시안이 돼요.'},
{id:'seabreeze', ko:'시브리즈', en:'Seabreeze', base:'보드카', flav:['상큼','청량'], abv:11, glass:'highball', liquid:'#d9485f', method:'빌드', diff:1, ice:true,
 ing:[['보드카',45,'ml','#c5d5e3'],['크랜베리 주스',90,'ml','#c72c4c'],['자몽 주스',15,'ml','#f0a49a']],
 steps:['하이볼 글라스에 얼음을 채워요.','보드카, 크랜베리 주스, 자몽 주스를 넣어요.','바 스푼으로 저어요.','라임 또는 레몬 웨지로 장식해요.'],
 garnish:'라임 또는 레몬 웨지', note:'크랜베리와 자몽의 새콤함이 바닷바람처럼 가벼운 하이볼이에요.'},
{id:'apple-martini', ko:'애플 마티니', en:'Apple Martini', base:'보드카', flav:['상큼','달콤'], abv:18, glass:'martini', liquid:'#b8e06a', method:'셰이크', diff:2,
 ing:[['보드카',30,'ml','#c5d5e3'],['애플 퍼커',30,'ml','#a8d94a'],['라임주스',15,'ml','#bfd85a']],
 steps:['셰이커에 얼음과 보드카, 애플 퍼커(사워 애플 리큐르), 라임주스를 넣어요.','10초쯤 세게 흔들어요.','차갑게 식힌 칵테일 글라스에 걸러 따라요.','사과 슬라이스로 장식해요.'],
 garnish:'사과 슬라이스', note:'사워 애플 리큐르로 풋사과 맛을 낸 마티니 스타일 칵테일이에요. 진과 베르무트가 들어가는 클래식 마티니와는 전혀 다른 맛이에요.'},
{id:'long-island-iced-tea', ko:'롱아일랜드 아이스티', en:'Long Island Iced Tea', base:'보드카', flav:['스트롱','달콤'], abv:17, glass:'collins', liquid:'#8a4a22', method:'빌드', diff:2, ice:true,
 ing:[['진',15,'ml','#b7d3ce'],['보드카',15,'ml','#c5d5e3'],['라이트 럼',15,'ml','#dad9bd'],['테킬라',15,'ml','#c5d5e3'],['트리플 섹',15,'ml','#f2b962'],['스위트 앤 사워 믹스',45,'ml','#f0e27a'],['콜라',30,'ml','#3a1c10']],
 steps:['콜린스 글라스에 얼음을 채워요.','진, 보드카, 라이트 럼, 테킬라, 트리플 섹, 스위트 앤 사워 믹스를 넣어요.','바 스푼으로 저은 뒤 콜라를 위에 채워요.','라임 또는 레몬 웨지로 장식해요.'],
 garnish:'라임 또는 레몬 웨지', note:'홍차가 한 방울도 들어가지 않지만 콜라로 아이스티 색을 내요. 다섯 가지 술이 들어가 보기보다 도수가 높아요.'},
/* ---- 테킬라 ---- */
{id:'margarita', ko:'마가리타', en:'Margarita', base:'테킬라', flav:['상큼'], abv:25, glass:'coupe', liquid:'#e4ecb0', method:'셰이크', diff:2,
 ing:[['테킬라',50,'ml',C.tequila],['쿠앵트로',20,'ml',C.cointreau],['라임주스',15,'ml',C.lime]],
 steps:['잔 가장자리에 라임을 문질러 소금을 묻혀요. 취향에 따라 생략해도 돼요.','셰이커에 얼음과 재료를 넣고 강하게 흔들어요.','차갑게 식힌 쿠페 글라스에 걸러 따라요.','라임 휠로 장식해요.'],
 garnish:'소금 림, 라임 휠', note:'소금이 신맛과 단맛을 또렷하게 잡아줘요. 잔 바깥쪽만 묻히면 음료에 소금이 섞이지 않아요.'},
{id:'paloma', ko:'팔로마', en:'Paloma', base:'테킬라', flav:['청량','상큼'], abv:11, glass:'highball', liquid:'#f1a39a', method:'빌드', diff:1, ice:true,
 ing:[['테킬라',50,'ml',C.tequila],['라임주스',15,'ml',C.lime],['자몽 소다',100,'ml',C.grapefruit]],
 steps:['하이볼 글라스 가장자리에 소금을 묻히고 얼음을 채워요.','테킬라와 라임주스를 넣어요.','자몽 소다를 채워 가볍게 저어요.','자몽 슬라이스나 라임으로 장식해요.'],
 garnish:'자몽 슬라이스, 소금 림', note:'멕시코에서 가장 즐겨 마신다고 알려진 테킬라 칵테일이에요. 재료가 단순해 집에서 만들기 좋아요.'},
{id:'tequila-sunrise', ko:'테킬라 선라이즈', en:'Tequila Sunrise', base:'테킬라', flav:['달콤','상큼'], abv:11, glass:'highball', liquid:'#f5b02f', liquid2:'#c4142c', method:'빌드', diff:1, ice:true,
 ing:[['테킬라',45,'ml',C.tequila],['오렌지주스',90,'ml',C.orange],['그레나딘',15,'ml',C.grenadine]],
 steps:['하이볼 글라스에 얼음을 채우고 테킬라와 오렌지주스를 넣어 저어요.','그레나딘을 잔 벽을 따라 천천히 부어 바닥에 가라앉혀요.','젓지 말고 그라데이션을 그대로 살려요.','오렌지 슬라이스와 체리를 올려요.'],
 garnish:'오렌지 슬라이스, 체리', note:'해가 뜨는 하늘을 닮은 층이 매력이에요. 저으면 색이 섞이니 마지막엔 손대지 마세요.'},

/* ---- 브랜디 ---- */
{id:'sidecar', ko:'사이드카', en:'Sidecar', base:'브랜디', flav:['상큼','스트롱'], abv:24, glass:'coupe', liquid:'#e3a13f', method:'셰이크', diff:2,
 ing:[['코냑',50,'ml',C.cognac],['쿠앵트로',20,'ml',C.cointreau],['레몬주스',20,'ml',C.lemon]],
 steps:['셰이커에 얼음과 모든 재료를 넣어요.','10초 흔들어요.','차가운 쿠페 글라스에 걸러 따라요.','오렌지 껍질로 장식해요. 취향에 따라 잔 가장자리에 설탕을 묻혀요.'],
 garnish:'오렌지 필', note:'브랜디 베이스 칵테일의 대표 주자예요. 코냑 대신 일반 브랜디를 써도 좋아요.'},

{id:'brandy-alexander', ko:'브랜디 알렉산더', en:'Brandy Alexander', base:'브랜디', flav:['달콤','부드러운'], abv:17, glass:'martini', liquid:'#c9a27a', method:'셰이크', diff:2,
 ing:[['브랜디',22.5,'ml','#b8621f'],['크렘 드 카카오(브라운)',22.5,'ml','#6b3a1e'],['우유',22.5,'ml','#f4efe6']],
 steps:['셰이커에 얼음과 브랜디, 크렘 드 카카오(브라운), 우유를 넣어요.','15초쯤 세게 흔들어 거품을 내요.','차갑게 식힌 칵테일 글라스에 걸러 따라요.','넛메그 가루를 위에 뿌려요.'],
 garnish:'넛메그 가루', note:'초콜릿 리큐르와 우유로 디저트처럼 부드러운 브랜디 칵테일이에요. 장식인 넛메그 가루를 빠뜨리지 않도록 주의하세요.'},
{id:'honeymoon', ko:'허니문', en:'Honeymoon Cocktail', base:'브랜디', flav:['상큼','달콤'], abv:24, glass:'martini', liquid:'#e0a64a', method:'셰이크', diff:2,
 ing:[['애플 브랜디',22.5,'ml','#c98a3a'],['베네딕틴 D.O.M.',22.5,'ml','#d4a23c'],['트리플 섹',7.5,'ml','#f2b962'],['레몬주스',15,'ml','#f0e070']],
 steps:['셰이커에 얼음과 모든 재료를 넣어요.','10초쯤 세게 흔들어요.','차갑게 식힌 칵테일 글라스에 걸러 따라요.'],
 garnish:'없음', note:'사과 브랜디에 약초 리큐르 베네딕틴을 섞어 은은한 허브 향이 나는 칵테일이에요.'},
/* ---- 와인·리큐르 ---- */
{id:'aperol-spritz', ko:'아페롤 스프리츠', en:'Aperol Spritz', base:'와인·리큐르', flav:['쌉쌀','청량'], abv:8, glass:'wine', liquid:'#f2662b', method:'빌드', diff:1, ice:true,
 ing:[['프로세코',60,'ml',C.prosecco],['아페롤',40,'ml',C.aperol],['소다수',20,'ml',C.soda]],
 steps:['와인 글라스에 얼음을 채워요.','프로세코, 아페롤 순으로 부어요.','소다수를 살짝 넣고 한 번만 저어요.','오렌지 슬라이스를 올려요.'],
 garnish:'오렌지 슬라이스', note:'도수가 낮고 쌉쌀해서 식전주로 인기가 많아요. 3:2:1 비율로 기억해도 좋아요.'},
{id:'mimosa', ko:'미모사', en:'Mimosa', base:'와인·리큐르', flav:['상큼','청량'], abv:6, glass:'flute', liquid:'#f6c25a', method:'빌드', diff:1,
 ing:[['스파클링 와인',75,'ml',C.sparkling],['오렌지주스',75,'ml',C.orange]],
 steps:['차가운 플루트 글라스에 스파클링 와인을 먼저 반쯤 따라요.','차게 식힌 오렌지주스를 부어요.','저으면 기포가 사라지니 그대로 내요.'],
 garnish:'없음 (오렌지 필 선택)', note:'브런치의 단골 메뉴예요. 재료를 모두 충분히 차게 준비하면 기포가 오래 가요.'},

{id:'kir', ko:'키르', en:'Kir', base:'와인·리큐르', flav:['상큼','달콤'], abv:11, glass:'wine', liquid:'#c25b7a', method:'빌드', diff:1,
 ing:[['화이트 와인',90,'ml','#f1e7b0'],['크렘 드 카시스',15,'ml','#5a1a3a']],
 steps:['화이트 와인 글라스에 차갑게 식힌 화이트 와인을 따라요.','크렘 드 카시스를 넣고 가볍게 저어요.','레몬 껍질을 비틀어 향을 입히고 올려요.'],
 garnish:'레몬 필', note:'프랑스 디종 시장의 이름을 딴 식전주예요. 화이트 와인 대신 샴페인을 쓰면 키르 로열이 돼요.'},
{id:'apricot', ko:'애프리콧', en:'Apricot Cocktail', base:'와인·리큐르', flav:['상큼','달콤'], abv:13, glass:'martini', liquid:'#eba050', method:'셰이크', diff:2,
 ing:[['애프리콧 브랜디',45,'ml','#e0913a'],['진',1,'tsp',null],['레몬주스',15,'ml','#f0e070'],['오렌지 주스',15,'ml','#f5992a']],
 steps:['셰이커에 얼음과 모든 재료를 넣어요.','10초쯤 세게 흔들어요.','차갑게 식힌 칵테일 글라스에 걸러 따라요.'],
 garnish:'없음', note:'살구 향 브랜디 리큐르를 베이스로 한 칵테일이에요. 진은 1tsp만 들어가니 양을 헷갈리지 마세요.'},
{id:'grasshopper', ko:'그래스호퍼', en:'Grasshopper', base:'와인·리큐르', flav:['달콤','부드러운'], abv:13, glass:'coupe', liquid:'#a8d9a0', method:'셰이크', diff:2,
 ing:[['크렘 드 멘트(그린)',30,'ml','#3fa35a'],['크렘 드 카카오(화이트)',30,'ml','#efe6d2'],['우유',30,'ml','#f4efe6']],
 steps:['셰이커에 얼음과 크렘 드 멘트(그린), 크렘 드 카카오(화이트), 우유를 넣어요.','15초쯤 세게 흔들어요.','쿠페 글라스에 걸러 따라요.'],
 garnish:'없음', note:'민트와 초콜릿 리큐르에 우유를 섞은 연녹색 디저트 칵테일이에요. "메뚜기"라는 이름처럼 색이 특징이에요.'},
{id:'june-bug', ko:'준 벅', en:'June Bug', base:'와인·리큐르', flav:['달콤','상큼'], abv:5, glass:'collins', liquid:'#b6d95a', method:'셰이크', diff:2, ice:true,
 ing:[['미도리(멜론 리큐르)',30,'ml','#7cc242'],['코코넛 럼',15,'ml','#f4efe2'],['바나나 리큐르',15,'ml','#f1e27a'],['파인애플 주스',60,'ml','#f1cd47'],['스위트 앤 사워 믹스',60,'ml','#f0e27a']],
 steps:['셰이커에 얼음과 모든 재료를 넣어요.','10초쯤 세게 흔들어요.','얼음을 채운 콜린스 글라스에 따라요.','파인애플 웨지와 체리로 장식해요.'],
 garnish:'파인애플 웨지, 체리', note:'멜론 리큐르의 연두색이 특징인 달콤한 트로피컬 칵테일이에요.'},
{id:'b-52', ko:'B-52', en:'B-52', base:'와인·리큐르', flav:['달콤','부드러운'], abv:26, glass:'sherry', liquid:'#d98a2b', liquid2:'#3b2319', method:'플로트', diff:3,
 ing:[['커피 리큐르',20,'ml','#3b2319'],['베일리스 아이리시 크림',20,'ml','#d9c3a0'],['그랑 마니에르',20,'ml','#d98a2b']],
 steps:['셰리 글라스에 커피 리큐르를 먼저 따라요.','바 스푼 뒷면을 잔 안쪽에 대고 베일리스를 천천히 흘려 층을 만들어요.','같은 방법으로 그랑 마니에르를 맨 위에 띄워요.'],
 garnish:'없음', note:'커피 리큐르, 아이리시 크림, 오렌지 리큐르를 차례로 띄운 3층 칵테일이에요. 각 재료를 1/3씩 같은 높이로 쌓는 것이 포인트예요.'},
{id:'pousse-cafe', ko:'푸스카페', en:'Pousse Cafe', base:'와인·리큐르', flav:['달콤'], abv:22, glass:'liqueur', liquid:'#3fa35a', liquid2:'#c4142c', method:'플로트', diff:3,
 ing:[['그레나딘 시럽',10,'ml','#c4142c'],['크렘 드 멘트(그린)',10,'ml','#3fa35a'],['브랜디',10,'ml','#b8621f']],
 steps:['스템드 리큐르 글라스에 그레나딘 시럽을 먼저 따라요.','바 스푼 뒷면을 타고 크렘 드 멘트(그린)를 천천히 흘려 층을 만들어요.','같은 방법으로 브랜디를 맨 위에 띄워요.'],
 garnish:'없음', note:'재료의 비중 차이로 층을 쌓는 칵테일이에요. 무거운 그레나딘, 크렘 드 멘트, 브랜디 순서를 지켜야 층이 섞이지 않아요.'},
/* ---- 우리술 ---- */
{id:'geumsan', ko:'금산', en:'Geumsan', base:'우리술', flav:['쌉쌀','달콤'], abv:25, glass:'martini', liquid:'#8a5a2a', method:'셰이크', diff:2,
 ing:[['금산 인삼주',45,'ml','#d9b35a'],['커피 리큐르',15,'ml','#3b2319'],['애플 퍼커',15,'ml','#a8d94a'],['라임주스',1,'tsp',null]],
 steps:['셰이커에 얼음과 금산 인삼주, 커피 리큐르, 애플 퍼커, 라임주스를 넣어요.','10초쯤 세게 흔들어요.','차갑게 식힌 칵테일 글라스에 걸러 따라요.'],
 garnish:'없음', note:'충남 금산의 인삼주를 베이스로 한 전통주 칵테일이에요. 인삼의 쌉쌀함에 커피와 사과 향이 어우러져요.'},
{id:'jindo', ko:'진도', en:'Jindo', base:'우리술', flav:['달콤','상큼'], abv:15, glass:'martini', liquid:'#c2344a', method:'셰이크', diff:2,
 ing:[['진도 홍주',30,'ml','#b0202d'],['크렘 드 멘트(화이트)',15,'ml','#eef2ee'],['청포도 주스',22.5,'ml','#dfe8b0'],['라즈베리 시럽',15,'ml','#c2244a']],
 steps:['셰이커에 얼음과 진도 홍주, 크렘 드 멘트(화이트), 청포도 주스, 라즈베리 시럽을 넣어요.','10초쯤 세게 흔들어요.','차갑게 식힌 칵테일 글라스에 걸러 따라요.'],
 garnish:'없음', note:'붉은 빛이 나는 전남 진도의 홍주를 베이스로 한 전통주 칵테일이에요. 민트 리큐르가 들어가 뒷맛이 상쾌해요.'},
{id:'puppy-love', ko:'풋사랑', en:'Puppy Love', base:'우리술', flav:['상큼','달콤'], abv:18, glass:'martini', liquid:'#cfe89a', method:'셰이크', diff:2,
 ing:[['안동소주',30,'ml','#eef0ee'],['트리플 섹',10,'ml','#f2b962'],['애플 퍼커',30,'ml','#a8d94a'],['라임주스',10,'ml','#bfd85a']],
 steps:['셰이커에 얼음과 안동소주, 트리플 섹, 애플 퍼커, 라임주스를 넣어요.','10초쯤 세게 흔들어요.','차갑게 식힌 칵테일 글라스에 걸러 따라요.','사과 슬라이스로 장식해요.'],
 garnish:'사과 슬라이스', note:'안동소주에 풋사과 리큐르를 더해 이름처럼 새콤달콤한 전통주 칵테일이에요.'},
{id:'healing', ko:'힐링', en:'Healing', base:'우리술', flav:['달콤','상큼'], abv:20, glass:'martini', liquid:'#b0463a', method:'셰이크', diff:2,
 ing:[['감홍로',45,'ml','#c7962b'],['베네딕틴 D.O.M.',10,'ml','#d4a23c'],['크렘 드 카시스',10,'ml','#5a1a3a'],['스위트 앤 사워 믹스',30,'ml','#f0e27a']],
 steps:['셰이커에 얼음과 감홍로, 베네딕틴 D.O.M., 크렘 드 카시스, 스위트 앤 사워 믹스를 넣어요.','10초쯤 세게 흔들어요.','차갑게 식힌 칵테일 글라스에 걸러 따라요.','레몬 껍질을 비틀어 향을 입히고 올려요.'],
 garnish:'레몬 필', note:'약재로 향을 낸 증류주 감홍로를 베이스로 한 전통주 칵테일이에요. 약초 리큐르와 카시스가 감홍로의 향을 부드럽게 감싸요.'},
{id:'gochang', ko:'고창', en:'Gochang', base:'우리술', flav:['달콤','청량'], abv:8, glass:'flute', liquid:'#7a1a32', method:'스터', diff:2,
 ing:[['선운산 복분자주',60,'ml','#5a1428'],['트리플 섹',15,'ml','#f2b962'],['스프라이트',60,'ml','#e7f3e8']],
 steps:['믹싱 글라스에 얼음과 복분자주, 트리플 섹을 넣고 저어요.','플루트 글라스에 걸러 따라요.','스프라이트를 채우고 가볍게 저어요.'],
 garnish:'없음', note:'전북 고창 선운산의 복분자주를 베이스로 한 전통주 칵테일이에요. 스프라이트의 탄산이 복분자의 단맛을 가볍게 해줘요.'},
/* ---- 논알콜 ---- */
{id:'virgin-mojito', ko:'버진 모히토', en:'Virgin Mojito', base:'논알콜', flav:['상큼','청량'], abv:0, glass:'highball', liquid:'#d6e8ae', method:'빌드', diff:1, ice:true,
 ing:[['라임주스',30,'ml',C.lime],['심플 시럽',20,'ml',C.syrup],['민트 잎',8,'잎','#5aa469'],['소다수',100,'ml',C.soda]],
 steps:['하이볼 글라스에 라임주스, 시럽, 민트 잎을 넣고 가볍게 눌러요.','부순 얼음을 가득 채워요.','소다수를 부어 아래에서 위로 저어요.','민트 가지와 라임 슬라이스로 장식해요.'],
 garnish:'민트 가지, 라임 슬라이스', note:'럼만 뺀 모히토예요. 술 대신 진저에일을 조금 더하면 깊은 맛이 살아나요.'},
{id:'shirley-temple', ko:'셜리 템플', en:'Shirley Temple', base:'논알콜', flav:['달콤','청량'], abv:0, glass:'highball', liquid:'#e6c75a', liquid2:'#c4142c', method:'빌드', diff:1, ice:true,
 ing:[['진저에일',150,'ml',C.gingerale],['그레나딘',15,'ml',C.grenadine],['라임주스',10,'ml',C.lime]],
 steps:['하이볼 글라스에 얼음을 채우고 진저에일을 부어요.','그레나딘을 넣어 가라앉혀요. 저으면 색이 섞여요.','라임주스를 살짝 더해요.','체리를 올려요.'],
 garnish:'체리', note:'아이들도 즐길 수 있는 논알콜 칵테일의 대명사예요. 그레나딘의 양으로 단맛을 조절하세요.'},
{id:'cinderella', ko:'신데렐라', en:'Cinderella', base:'논알콜', flav:['상큼','달콤'], abv:0, glass:'highball', liquid:'#f6b444', method:'셰이크', diff:1, ice:true,
 ing:[['오렌지주스',40,'ml',C.orange],['파인애플 주스',40,'ml',C.pineapple],['레몬주스',20,'ml',C.lemon],['그레나딘',1,'dash',null]],
 steps:['셰이커에 얼음과 세 가지 주스를 넣어요.','10초 흔들어요.','얼음을 채운 하이볼 글라스에 걸러 따르고 그레나딘을 더해요.'],
 garnish:'오렌지 슬라이스', note:'가장 유명한 논알콜 칵테일 중 하나예요. 레시피는 바마다 조금씩 달라요.'},
{id:'virgin-colada', ko:'버진 피냐 콜라다', en:'Virgin Piña Colada', base:'논알콜', flav:['달콤','부드러운'], abv:0, glass:'hurricane', liquid:'#f4ecd0', method:'블렌드', diff:1,
 ing:[['파인애플 주스',90,'ml',C.pineapple],['코코넛 크림',30,'ml',C.coconut]],
 steps:['블렌더에 파인애플 주스와 코코넛 크림을 넣어요.','얼음 한 컵을 넣고 곱게 갈아요.','허리케인 글라스에 따르고 파인애플 웨지으로 장식해요.'],
 garnish:'파인애플 웨지', note:'얼린 파인애플을 쓰면 얼음이 적어도 시원하고 진하게 만들 수 있어요.'},
{id:'arnold-palmer', ko:'아놀드 파머', en:'Arnold Palmer', base:'논알콜', flav:['상큼','쌉쌀'], abv:0, glass:'highball', liquid:'#c98a3a', liquid2:'#e8d16a', method:'빌드', diff:1, ice:true,
 ing:[['홍차(차갑게)',120,'ml',C.tea],['레몬주스',30,'ml',C.lemon],['심플 시럽',25,'ml',C.syrup]],
 steps:['홍차를 진하게 우려 식혀 두어요.','하이볼 글라스에 얼음을 채우고 차, 레몬주스, 시럽을 넣어요.','잘 저어 섞어요.','레몬 슬라이스로 장식해요.'],
 garnish:'레몬 슬라이스', note:'아이스티와 레모네이드를 반씩 섞은 음료로, 골프 선수 아놀드 파머가 즐겨 마셨던 데서 이름이 붙었다고 알려져 있어요.'},
{id:'ginger-mule', ko:'진저 뮬', en:'Ginger Mule', base:'논알콜', flav:['청량','상큼'], abv:0, glass:'mug', liquid:'#e6cc70', method:'빌드', diff:1, ice:true,
 ing:[['진저비어',150,'ml',C.gingerbeer],['라임주스',20,'ml',C.lime]],
 steps:['코퍼 머그에 얼음을 가득 채워요.','라임주스를 넣고 진저비어를 부어요.','가볍게 저어 라임 웨지와 민트로 장식해요.'],
 garnish:'라임 웨지, 민트 가지', note:'모스코 뮬에서 보드카만 뺀 논알콜 버전이에요. 매운 진저비어를 고르면 술 없이도 알싸한 맛이 살아요.'},
{id:'virgin-mary', ko:'버진 메리', en:'Virgin Mary', base:'논알콜', flav:['감칠맛'], abv:0, glass:'highball', liquid:'#c0331f', method:'빌드', diff:1, ice:true,
 ing:[['토마토 주스',120,'ml',C.tomato],['레몬주스',15,'ml',C.lemon],['우스터 소스',2,'dash',null],['타바스코',2,'dash',null],['소금·후추','한 꼬집','',null]],
 steps:['하이볼 글라스에 얼음을 채워요.','토마토 주스와 레몬주스를 넣어요.','우스터 소스, 타바스코, 소금, 후추를 더하고 저어요.','셀러리 스틱으로 장식해요.'],
 garnish:'셀러리 스틱', note:'블러디 메리에서 보드카만 뺀 음료예요. 토마토 주스 자체의 맛이 중요하니 좋은 제품을 고르세요.'},
{id:'fresh-lemon-squash', ko:'프레시 레몬 스쿼시', en:'Fresh Lemon Squash', base:'논알콜', flav:['상큼','청량'], abv:0, glass:'highball', liquid:'#f3eeb0', method:'빌드', diff:1, ice:true,
 ing:[['생레몬',0.5,'개','#f0e070'],['슈거 파우더',2,'tsp',null],['소다수',120,'ml','#cde4ee']],
 steps:['레몬 1/2개를 짜서 즙을 하이볼 글라스에 넣어요.','슈거 파우더를 넣고 잘 녹여요.','얼음을 채우고 소다수를 가득 따른 뒤 저어요.','레몬 슬라이스로 장식해요.'],
 garnish:'레몬 슬라이스', note:'생레몬즙에 설탕과 소다수만 더한 무알콜 음료예요. 레몬을 직접 짜는 것이 핵심이에요.'},
{id:'virgin-fruit-punch', ko:'버진 프루트 펀치', en:'Virgin Fruit Punch', base:'논알콜', flav:['달콤','상큼'], abv:0, glass:'pilsner', liquid:'#f08a5a', method:'블렌드', diff:1, ice:true,
 ing:[['오렌지 주스',30,'ml','#f5992a'],['파인애플 주스',30,'ml','#f1cd47'],['크랜베리 주스',30,'ml','#c72c4c'],['자몽 주스',30,'ml','#f0a49a'],['레몬주스',15,'ml','#f0e070'],['그레나딘 시럽',15,'ml','#c4142c']],
 steps:['블렌더에 잘게 부순 얼음과 모든 재료를 넣어요.','부드러워질 때까지 갈아요.','풋티드 필스너 글라스에 따라요.','파인애플 웨지와 체리로 장식해요.'],
 garnish:'파인애플 웨지, 체리', note:'네 가지 과일 주스에 레몬과 그레나딘을 더해 블렌더로 섞은 무알콜 펀치예요.'}
];
/* ---------- 조주기능사 실기 표준 레시피 ----------
   출처: 국가기술자격 실기시험 표준레시피(한국산업인력공단, 2024년 제1회 실기시험부터 적용).
   번호·영문 표기·조주법·글라스·가니시·재료는 공식 표 그대로 옮겼어요. ko는 시험 한글 표기예요.
   재료 용량은 oz 원문을 두고, 화면에서 mL를 함께 보여줘요(1oz = 30mL). */
const EXAM_SOURCE = '국가기술자격 실기시험 표준레시피 (한국산업인력공단, 2024년 적용)';
const EXAM = {
  'pousse-cafe':{no:1, en:'Pousse Cafe', ko:'푸스카페', method:'Float', glass:'Stemed Liqueur Glass', garnish:'없음',
    ing:[['Grenadine Syrup','1/3part'],['Crème De Menthe(Green)','1/3part'],['Brandy','1/3part']]},
  'manhattan':{no:2, en:'Manhattan', ko:'맨해튼', method:'Stir', glass:'Cocktail Glass', garnish:'Cherry',
    ing:[['Bourbon Whiskey','1 1/2oz'],['Sweet Vermouth','3/4oz'],['Angostura Bitters','1dash']]},
  'martini':{no:3, en:'Dry Martini', ko:'드라이 마티니', method:'Stir', glass:'Cocktail Glass', garnish:'Green Olive',
    ing:[['Dry Gin','2oz'],['Dry Vermouth','1/3oz']]},
  'old-fashioned':{no:4, en:'Old Fashioned', ko:'올드 패션드', method:'Build', glass:'Old-fashioned Glass', garnish:'A Slice of Orange and Cherry',
    ing:[['Bourbon Whiskey','1 1/2oz'],['Powdered Sugar','1tsp'],['Angostura Bitters','1dash'],['Soda Water','1/2oz']]},
  'brandy-alexander':{no:5, en:'Brandy Alexander', ko:'브랜디 알렉산더', method:'Shake', glass:'Cocktail Glass', garnish:'Nutmeg Powder',
    ing:[['Brandy','3/4oz'],['Crème De Cacao(Brown)','3/4oz'],['Light Milk','3/4oz']]},
  'singapore-sling':{no:6, en:'Singapore Sling', ko:'싱가포르 슬링', method:'Shake/Build', glass:'Footed Pilsner Glass', garnish:'A Slice of Orange and Cherry',
    ing:[['Dry Gin','1 1/2oz'],['Lemon Juice','1/2oz'],['Powdered Sugar','1tsp'],['Soda Water','Fill'],['Cherry Flavored Brandy','On Top 1/2oz']]},
  'black-russian':{no:7, en:'Black Russian', ko:'블랙 러시안', method:'Build', glass:'Old-fashioned Glass', garnish:'없음',
    ing:[['Vodka','1oz'],['Coffee Liqueur','1/2oz']]},
  'margarita':{no:8, en:'Margarita', ko:'마르가리타', method:'Shake', glass:'Cocktail Glass', garnish:'Rimming with Salt',
    ing:[['Tequila','1 1/2oz'],['Cointreau or Triple Sec','1/2oz'],['Lime Juice','1/2oz']]},
  'rusty-nail':{no:9, en:'Rusty Nail', ko:'러스티 네일', method:'Build', glass:'Old-fashioned Glass', garnish:'없음',
    ing:[['Scotch Whisky','1oz'],['Drambuie','1/2oz']]},
  'whiskey-sour':{no:10, en:'Whiskey Sour', ko:'위스키 사워', method:'Shake/Build', glass:'Sour Glass', garnish:'A Slice of Lemon and Cherry',
    ing:[['Bourbon Whiskey','1 1/2oz'],['Lemon Juice','1/2oz'],['Powdered Sugar','1tsp'],['Soda Water','On Top 1oz']]},
  'new-york':{no:11, en:'New York', ko:'뉴욕', method:'Shake', glass:'Cocktail Glass', garnish:'Twist of Lemon peel',
    ing:[['Bourbon Whiskey','1 1/2oz'],['Lime Juice','1/2oz'],['Powdered Sugar','1tsp'],['Grenadine Syrup','1/2tsp']]},
  'daiquiri':{no:12, en:'Daiquiri', ko:'다이키리', method:'Shake', glass:'Cocktail Glass', garnish:'없음',
    ing:[['Light Rum','1 3/4oz'],['Lime Juice','3/4oz'],['Powdered Sugar','1tsp']]},
  'b-52':{no:13, en:'B-52', ko:'비-52', method:'Float', glass:'Sherry Glass(2oz)', garnish:'없음',
    ing:[['Coffee Liqueur','1/3part'],["Bailey's Irish Cream Liqueur",'1/3part'],['Grand Marnier','1/3part']]},
  'june-bug':{no:14, en:'June Bug', ko:'준 벅', method:'Shake', glass:'Collins Glass', garnish:'A Wedge of fresh Pineapple & Cherry',
    ing:[['Midori(Melon Liqueur)','1oz'],['Coconut Flavored Rum','1/2oz'],['Banana Liqueur','1/2oz'],['Pineapple Juice','2oz'],['Sweet & Sour mix','2oz']]},
  'bacardi':{no:15, en:'Bacardi Cocktail', ko:'바카디', method:'Shake', glass:'Cocktail Glass', garnish:'없음',
    ing:[['Bacardi Rum White','1 3/4oz'],['Lime Juice','3/4oz'],['Grenadine Syrup','1tsp']]},
  'cuba-libre':{no:16, en:'Cuba Libre', ko:'쿠바 리브레', method:'Build', glass:'Highball Glass', garnish:'A Wedge of Lemon',
    ing:[['Light Rum','1 1/2oz'],['Lime Juice','1/2oz'],['Cola','Fill']]},
  'grasshopper':{no:17, en:'Grasshopper', ko:'그래스호퍼', method:'Shake', glass:'Champagne Glass(saucer형)', garnish:'없음',
    ing:[['Crème De Menthe(Green)','1oz'],['Crème De Cacao(White)','1oz'],['Light Milk','1oz']]},
  'seabreeze':{no:18, en:'Seabreeze', ko:'시브리즈', method:'Build', glass:'Highball Glass', garnish:'A Wedge of Lime or Lemon',
    ing:[['Vodka','1 1/2oz'],['Cranberry Juice','3oz'],['Grapefruit Juice','1/2oz']]},
  'apple-martini':{no:19, en:'Apple Martini', ko:'애플 마티니', method:'Shake', glass:'Cocktail Glass', garnish:'A Slice of Apple',
    ing:[['Vodka','1oz'],['Apple Pucker(Sour apple Liqueur)','1oz'],['Lime Juice','1/2oz']]},
  'negroni':{no:20, en:'Negroni', ko:'니그로니', method:'Build', glass:'Old-fashioned Glass', garnish:'Twist of Lemon peel',
    ing:[['Dry Gin','3/4oz'],['Sweet Vermouth','3/4oz'],['Campari','3/4oz']]},
  'long-island-iced-tea':{no:21, en:'Long Island Iced Tea', ko:'롱아일랜드 아이스티', method:'Build', glass:'Collins Glass', garnish:'A Wedge of Lime or Lemon',
    ing:[['Dry Gin','1/2oz'],['Vodka','1/2oz'],['Light Rum','1/2oz'],['Tequila','1/2oz'],['Triple Sec','1/2oz'],['Sweet & Sour Mix','1 1/2oz'],['Cola','On Top']]},
  'sidecar':{no:22, en:'Sidecar', ko:'사이드 카', method:'Shake', glass:'Cocktail Glass', garnish:'없음',
    ing:[['Brandy','1oz'],['Triple Sec','1oz'],['Lemon Juice','1/4oz']]},
  'mai-tai':{no:23, en:'Mai-Tai', ko:'마이타이', method:'Blend', glass:'Footed Pilsner Glass', garnish:'A Wedge of fresh Pineapple(Orange) & Cherry',
    ing:[['Light Rum','1 1/4oz'],['Triple Sec','3/4oz'],['Lime Juice','1oz'],['Pineapple Juice','1oz'],['Orange Juice','1oz'],['Grenadine Syrup','1/4oz']]},
  'pina-colada':{no:24, en:'Pina Colada', ko:'피냐콜라다', method:'Blend', glass:'Footed Pilsner Glass', garnish:'A Wedge of fresh Pineapple & Cherry',
    ing:[['Light Rum','1 1/4oz'],['Pina Colada Mix','2oz'],['Pineapple Juice','2oz']]},
  'cosmopolitan':{no:25, en:'Cosmopolitan Cocktail', ko:'코즈모폴리턴', method:'Shake', glass:'Cocktail Glass', garnish:'Twist of Lime or Lemon peel',
    ing:[['Vodka','1oz'],['Triple Sec','1/2oz'],['Lime Juice','1/2oz'],['Cranberry Juice','1/2oz']]},
  'moscow-mule':{no:26, en:'Moscow Mule', ko:'모스코 뮬', method:'Build', glass:'Highball Glass', garnish:'A Slice of Lime or Lemon',
    ing:[['Vodka','1 1/2oz'],['Lime Juice','1/2oz'],['Ginger ale','Fill']]},
  'apricot':{no:27, en:'Apricot Cocktail', ko:'애프리콧', method:'Shake', glass:'Cocktail Glass', garnish:'없음',
    ing:[['Apricot Flavored Brandy','1 1/2oz'],['Dry Gin','1tsp'],['Lemon Juice','1/2oz'],['Orange Juice','1/2oz']]},
  'honeymoon':{no:28, en:'Honeymoon Cocktail', ko:'허니문', method:'Shake', glass:'Cocktail Glass', garnish:'없음',
    ing:[['Apple Brandy','3/4oz'],['Benedictine DOM','3/4oz'],['Triple Sec','1/4oz'],['Lemon Juice','1/2oz']]},
  'blue-hawaiian':{no:29, en:'Blue Hawaiian', ko:'블루 하와이언', method:'Blend', glass:'Footed Pilsner Glass', garnish:'A Wedge of fresh Pineapple & Cherry',
    ing:[['Light Rum','1oz'],['Blue Curacao','1oz'],['Coconut Flavored Rum','1oz'],['Pineapple Juice','2 1/2oz']]},
  'kir':{no:30, en:'Kir', ko:'키르', method:'Build', glass:'White Wine Glass', garnish:'Twist of Lemon peel',
    ing:[['White Wine','3oz'],['Crème de Cassis','1/2oz']]},
  'tequila-sunrise':{no:31, en:'Tequila Sunrise', ko:'테킬라 선라이즈', method:'Build/Float', glass:'Footed Pilsner Glass', garnish:'없음',
    ing:[['Tequila','1 1/2oz'],['Orange Juice','Fill'],['Grenadine Syrup','1/2oz']]},
  'healing':{no:32, en:'Healing', ko:'힐링', method:'Shake', glass:'Cocktail Glass', garnish:'Twist of Lemon peel',
    ing:[['Gam Hong Ro(40도)','1 1/2oz'],['Benedictine DOM','1/3oz'],['Crème de Cassis','1/3oz'],['Sweet & Sour mix','1oz']]},
  'jindo':{no:33, en:'Jindo', ko:'진도', method:'Shake', glass:'Cocktail Glass', garnish:'없음',
    ing:[['Jindo Hong Ju(40도)','1oz'],['Crème de Menthe White','1/2oz'],['White Grape Juice(청포도주스)','3/4oz'],['Raspberry Syrup','1/2oz']]},
  'puppy-love':{no:34, en:'Puppy Love', ko:'풋사랑', method:'Shake', glass:'Cocktail Glass', garnish:'A Slice of Apple',
    ing:[['Andong Soju(35도)','1oz'],['Triple Sec','1/3oz'],['Apple Pucker(Sour apple Liqueur)','1oz'],['Lime Juice','1/3oz']]},
  'geumsan':{no:35, en:'Geumsan', ko:'금산', method:'Shake', glass:'Cocktail Glass', garnish:'없음',
    ing:[['Geumsan Insamju(43도)','1 1/2oz'],['Coffee Liqueur(Kahlúa)','1/2oz'],['Apple Pucker(Sour apple Liqueur)','1/2oz'],['Lime Juice','1tsp']]},
  'gochang':{no:36, en:'Gochang', ko:'고창', method:'Stir', glass:'Flute Champagne Glass', garnish:'없음',
    ing:[['Sunwoonsan bokbunja wine','2oz'],['Triple Sec','1/2oz'],['Sprite','2oz']]},
  'gin-fizz':{no:37, en:'Gin Fizz', ko:'진 피즈', method:'Shake/Build', glass:'Highball Glass', garnish:'A Slice of Lemon',
    ing:[['Dry Gin','1 1/2oz'],['Lemon Juice','1/2oz'],['Powdered Sugar','1tsp'],['Soda Water','Fill']]},
  'fresh-lemon-squash':{no:38, en:'Fresh Lemon Squash', ko:'프레시 레몬 스쿼시', method:'Build', glass:'Highball Glass', garnish:'A Slice of Lemon',
    ing:[['Fresh squeezed Lemon','1/2ea'],['Powdered Sugar','2tsp'],['Soda Water','Fill']]},
  'virgin-fruit-punch':{no:39, en:'Virgin Fruit Punch', ko:'버진 프루트 펀치', method:'Blend', glass:'Footed Pilsner Glass', garnish:'A Wedge of fresh Pineapple & Cherry',
    ing:[['Orange Juice','1oz'],['Pineapple Juice','1oz'],['Cranberry Juice','1oz'],['Grapefruit Juice','1oz'],['Lemon Juice','1/2oz'],['Grenadine Syrup','1/2oz']]},
  'boulevardier':{no:40, en:'Boulevardier', ko:'불바디에', method:'Stir', glass:'Old-fashioned Glass', garnish:'Twist of Orange peel',
    ing:[['Bourbon Whiskey','1oz'],['Sweet Vermouth','1oz'],['Campari','1oz']]}
};
// '1 1/2oz' → '1 1/2oz · 45mL', 'On Top 1/2oz' → 'On Top 1/2oz · 15mL', 'Fill' → 'Fill (잔을 채움)'
function examAmount(a){
  if(a==='Fill') return 'Fill (잔을 채움)';
  if(a==='On Top') return 'On Top (위에 채움)';
  const m = /^(On Top )?(?:(\d+) )?(?:(\d+)\/(\d+))?(\d+)?(oz|tsp)$/.exec(a);
  if(!m) return a;
  const n = (+m[2]||0) + (m[3] ? m[3]/m[4] : 0) + (+m[5]||0);
  const mlv = Math.round(n * (m[6]==='oz' ? 30 : 5) * 10) / 10;
  return `${a} · ${mlv}mL`;
}
RECIPES.forEach(r=>{ r.exam = EXAM[r.id] || null; });
const BY_ID = Object.fromEntries(RECIPES.map(r=>[r.id,r]));
RECIPES.forEach(r=>{
  r.glassName = GLASS[r.glass].name;
  r.hay = [r.ko,r.en,...(ALIAS[r.id]||[]),r.base,BASE_EN[r.base],r.glassName,...r.flav,...r.ing.map(i=>i[0]),...(r.exam?[r.exam.en,r.exam.ko,'조주기능사 실기']:[])].join(' ').toLowerCase();
  r.hayNs = r.hay.replace(/\s+/g,'');
});

/* ---------- 주류 상식 (조주기능사 필기 대비) ---------- */
const CATS = ['양조주','증류주','전통주','혼성주'];
const SPIRITS = [
{id:'beer', ko:'맥주', en:'Beer', cat:'양조주', material:'맥아, 홉, 물, 효모', process:'맥아를 당화해 맥즙을 만들고 홉을 더해 끓인 뒤 효모로 발효, 숙성·여과해요.', abv:'4–6%', types:'에일(상면발효) · 라거(하면발효)', note:'홉이 쓴맛과 향을 담당하고, 발효 온도·효모 종류로 에일과 라거가 갈려요.', glass:'highball', liquid:'#e9c86b',
 sub:[
   {name:'에일 Ale', abv:'4–7%', desc:'상면발효 효모로 상온(15–25℃)에서 발효. 향이 풍부하고 과일향이 도드라져요.'},
   {name:'라거 Lager', abv:'4–5%', desc:'하면발효 효모로 저온(7–15℃)에서 발효 후 저온 숙성. 깔끔하고 청량한 맛, 전 세계 생산량의 대부분을 차지해요.'},
   {name:'스타우트·포터 (흑맥주)', abv:'4–8%', desc:'볶은 맥아(로스티드 몰트)를 써서 짙은 색과 커피·초콜릿 향의 로스팅 풍미가 나요.'},
   {name:'밀맥주 Weizen', abv:'5–5.5%', desc:'맥아의 일부를 밀로 대체. 부드러운 질감과 바나나·정향 같은 과일·향신료 향이 특징이에요.'}
 ]},
{id:'wine', ko:'와인', en:'Wine', cat:'양조주', material:'포도', process:'포도를 으깬 뒤 껍질과 함께(레드) 또는 즙만(화이트) 발효시키고 오크통·병에서 숙성해요.', abv:'9–15%', types:'레드 · 화이트 · 로제 · 스파클링 · 주정강화(포트·셰리)', note:'껍질을 함께 발효하면 레드, 즙만 발효하면 화이트가 돼요.', glass:'wine', liquid:'#7a1f2b',
 sub:[
   {name:'스틸 와인', abv:'11–14%', desc:'탄산이 없는 일반 와인. 레드·화이트·로제로 나뉘어요.'},
   {name:'스파클링 와인', abv:'11–12.5%', desc:'병 또는 탱크에서 2차 발효로 탄산을 담은 와인. 샴페인은 프랑스 샹파뉴 지역산만 쓸 수 있는 명칭이에요.'},
   {name:'주정강화 와인 (포티파이드)', abv:'15–22%', desc:'발효 중 브랜디를 더해 도수를 높인 와인. 포트, 셰리, 마데이라가 대표적이에요.'},
   {name:'아로마타이즈드 와인', abv:'15–18%', desc:'허브·향료를 가미한 와인. 베르무트가 대표적이며 칵테일 부재료로 많이 쓰여요.'}
 ]},

{id:'whisky', ko:'위스키', en:'Whisky', cat:'증류주', material:'보리·호밀·옥수수 등 곡물', process:'곡물을 맥아화·당화한 뒤 발효, 단식 또는 연속식으로 증류하고 오크통에서 숙성해요.', abv:'40–50%', types:'스카치 · 버번 · 아이리시 · 캐나디안 · 재패니즈', note:'스카치 위스키는 오크통 최소 3년 숙성이 법적 요건이에요.', glass:'rocks', liquid:'#b1671f',
 sub:[
   {name:'싱글몰트 Single Malt', abv:'40–46% (캐스크 스트렝스 50–60%)', desc:'한 증류소에서, 발아시킨 보리(몰트)만으로 단식 증류해 만든 위스키.'},
   {name:'싱글그레인 Single Grain', abv:'40–46%', desc:'한 증류소에서, 옥수수 등 그레인을 주원료로 연속식 증류해 만든 위스키.'},
   {name:'블렌디드 몰트 Blended Malt', abv:'40–46%', desc:'여러 증류소의 싱글몰트 위스키들을 섞은 것 (옛 명칭: 배티드 몰트).'},
   {name:'블렌디드 그레인 Blended Grain', abv:'40–43%', desc:'여러 증류소의 싱글그레인 위스키들을 섞은 것.'},
   {name:'블렌디드 위스키 Blended', abv:'40–43%', desc:'몰트 원액과 그레인 원액을 섞은 위스키. 유통량이 가장 많은 대중적인 형태예요.'}
 ]},
{id:'brandy', ko:'브랜디', en:'Brandy', cat:'증류주', material:'과일(주로 포도)', process:'과일 발효주(와인)를 증류한 뒤 오크통에서 숙성해요.', abv:'40–45%', types:'코냑 · 아르마냑 · 칼바도스(사과 브랜디)', note:'코냑은 프랑스 코냑 지역 포도로만 만들고 VS·VSOP·XO 등급으로 나뉘어요.', glass:'rocks', liquid:'#a1521c',
 sub:[
   {name:'코냑 Cognac', abv:'40–45%', desc:'프랑스 코냑 지방 포도로 만든 브랜디. 2회 단식 증류 후 오크통 숙성, VS·VSOP·XO 등급으로 나뉘어요.'},
   {name:'아르마냑 Armagnac', abv:'40–48%', desc:'프랑스 아르마냑 지방산. 대부분 단식(연속) 증류를 1회만 거쳐 코냑보다 풍미가 진해요.'},
   {name:'칼바도스 Calvados', abv:'40–45%', desc:'사과(또는 배)를 발효·증류한 브랜디. 프랑스 노르망디 지역이 대표 산지예요.'},
   {name:'마르·그라파 Marc·Grappa', abv:'38–50%', desc:'와인을 짜고 남은 포도 껍질·씨(포마스)를 증류한 브랜디.'}
 ]},
{id:'gin', ko:'진', en:'Gin', cat:'증류주', material:'곡물 증류주 + 주니퍼베리 등 식물성 재료', process:'중성 곡물 증류주에 주니퍼베리와 여러 보태니컬을 넣어 재증류해요.', abv:'37.5–47%', types:'런던 드라이 · 올드 톰 · 플리머스', note:'주니퍼베리 향이 핵심이며, 칵테일 베이스로 가장 많이 쓰이는 증류주예요.', glass:'martini', liquid:'#d8e3c0',
 sub:[
   {name:'런던 드라이 진', abv:'37.5–47%', desc:'증류 후 인공 향료나 당분을 첨가하지 않는 드라이한 스타일. 가장 대중적인 진이에요.'},
   {name:'올드 톰 진', abv:'40–47%', desc:'런던 드라이보다 살짝 단맛을 더한 전통 스타일. 진의 옛 형태에 가까워요.'},
   {name:'플리머스 진', abv:'41.2% (네이비 스트렝스 57%)', desc:'영국 플리머스 지역에서만 생산되는 원산지 명칭 보호 진. 흙 내음이 도는 부드러운 향.'},
   {name:'제네버 Jenever', abv:'30–40%', desc:'네덜란드·벨기에의 진의 원형. 몰트 와인 베이스라 곡물 향이 진하게 남아있어요.'}
 ]},
{id:'vodka', ko:'보드카', en:'Vodka', cat:'증류주', material:'감자 또는 곡물', process:'발효 후 연속식으로 여러 번 증류하고 활성탄으로 여과해요.', abv:'40% 내외', types:'플레인 · 플레이버드', note:'무색·무취·무미에 가깝게 만드는 것이 특징으로, 활성탄 여과가 핵심 공정이에요.', glass:'martini', liquid:'#eef2ee',
 sub:[
   {name:'플레인 보드카', abv:'37.5–40%', desc:'향을 더하지 않은 기본형. 여과를 거듭할수록 순수하고 부드러워져요.'},
   {name:'플레이버드 보드카', abv:'30–40%', desc:'레몬·베리·허브 등의 향을 더한 보드카. 칵테일에 바로 개성을 더할 때 써요.'}
 ]},
{id:'rum', ko:'럼', en:'Rum', cat:'증류주', material:'사탕수수 또는 당밀', process:'당밀을 발효한 뒤 증류하고, 오크통 숙성 여부·기간으로 종류를 나눠요.', abv:'40% 내외', types:'화이트(라이트) · 골드 · 다크 · 스파이스드', note:'카리브해 지역이 주산지이고, 숙성 기간이 길수록 색이 짙어져요.', glass:'rocks', liquid:'#8a4a1e',
 sub:[
   {name:'화이트(라이트) 럼', abv:'37.5–40%', desc:'짧은 숙성 또는 여과로 무색에 가깝게 만들어요. 모히토·다이키리 등 칵테일 베이스로 많이 써요.'},
   {name:'골드 럼', abv:'40% 내외', desc:'단기 오크통 숙성으로 옅은 금색과 은은한 풍미가 생겨요.'},
   {name:'다크 럼', abv:'40–43%', desc:'장기 숙성으로 짙은 색과 진한 캐러멜·당밀 향이 나요.'},
   {name:'스파이스드 럼', abv:'35–40%', desc:'바닐라·계피 등 향신료를 더해 풍미를 강화한 럼.'}
 ]},
{id:'tequila', ko:'테킬라', en:'Tequila', cat:'증류주', material:'블루 아가베', process:'아가베를 쪄서 당화한 뒤 발효, 2회 증류해요.', abv:'35–55%', types:'블랑코(무숙성) · 레포사도(단기 숙성) · 아녜호(장기 숙성)', note:'멕시코 특정 지역에서만 생산 가능한 원산지 명칭 보호 품목이에요.', glass:'rocks', liquid:'#e4d9a0',
 sub:[
   {name:'블랑코(실버) Blanco', abv:'38–40%', desc:'숙성 없이 바로 병입. 아가베 본연의 풋풋한 향이 살아있어요.'},
   {name:'레포사도 Reposado', abv:'38–40%', desc:'오크통에서 2개월~1년 숙성. 부드러운 오크 향이 더해져요.'},
   {name:'아녜호 Añejo', abv:'38–40%', desc:'오크통에서 1~3년 숙성. 위스키·브랜디에 가까운 깊은 풍미.'},
   {name:'엑스트라 아녜호', abv:'38–40%', desc:'3년 이상 장기 숙성한 최고급 등급.'}
 ]},

{id:'takju', ko:'막걸리(탁주)', en:'Takju', cat:'전통주', material:'쌀, 누룩, 물', process:'찐 쌀에 누룩과 물을 더해 발효시킨 뒤 거르지 않고 탁하게 마무리해요.', abv:'6–8%', types:'생막걸리 · 살균 막걸리', note:'당화와 발효가 동시에 일어나는 한국 고유의 병행복발효 방식이에요.', glass:'highball', liquid:'#eef0e4',
 sub:[
   {name:'생막걸리', abv:'6% 내외', desc:'열처리를 하지 않아 효모가 살아있어요. 유통기한이 짧고 시간이 지날수록 맛이 변해요.'},
   {name:'살균 막걸리', abv:'6% 내외', desc:'열처리로 발효를 멈춰 유통기한을 늘린 막걸리.'}
 ]},
{id:'yakju', ko:'청주·약주', en:'Cheongju', cat:'전통주', material:'쌀, 누룩, 물', process:'막걸리와 같은 방식으로 빚은 뒤 맑게 걸러내요.', abv:'13–16%', types:'청주 · 약주', note:'탁주를 여과·숙성해 맑게 만든 술이에요.', glass:'flute', liquid:'#e8dfb8',
 sub:[
   {name:'청주', abv:'13–16%', desc:'쌀·누룩·물만으로 빚어 맑게 거른 술.'},
   {name:'약주', abv:'11–15%', desc:'청주에 한약재 등의 부재료를 더해 빚은 술.'}
 ]},
{id:'soju', ko:'소주', en:'Soju', cat:'전통주', material:'쌀·보리 등 곡물, 또는 주정', process:'전통 소주는 곡물을 발효한 뒤 단식 증류해요.', abv:'17–45%', types:'증류식 소주 · 희석식 소주', note:'희석식은 주정에 물을 타 만든 대중 소주로, 증류식 소주와 구분돼요.', glass:'rocks', liquid:'#f2f2ea',
 sub:[
   {name:'증류식 소주', abv:'17–45%', desc:'곡물을 발효한 뒤 단식 증류해, 원료 고유의 향이 살아있어요. 안동소주가 대표적이에요.'},
   {name:'희석식 소주', abv:'16–17%', desc:'연속식 증류로 만든 주정에 물과 감미료를 더한, 시중에 가장 흔한 소주.'}
 ]},

{id:'liqueur', ko:'혼성주(리큐르)', en:'Liqueur', cat:'혼성주', material:'증류주 + 과일·허브·향신료 + 당분', process:'증류주에 원료를 침출하거나 함께 증류해 향을 더하고 설탕을 넣어요.', abv:'15–55%', types:'오렌지계(쿠앵트로) · 허브계(캄파리) · 커피계(깔루아) · 크림계(베일리스)', note:'"증류주 + 당분 + 향료"라는 정의가 혼성주의 핵심이에요.', glass:'coupe', liquid:'#d98a2e',
 sub:[
   {name:'오렌지 리큐르', abv:'15–40%', desc:'쿠앵트로, 트리플 섹, 그랑 마니에르 등. 마가리타·코스모폴리탄 등에 두루 쓰여요.'},
   {name:'허브·비터 리큐르', abv:'11–55%', desc:'캄파리, 아페롤, 샤르트뢰즈, 베네딕틴 등. 쌉쌀한 맛으로 식전주 칵테일에 많이 써요.'},
   {name:'커피 리큐르', abv:'16–25%', desc:'깔루아, 티아 마리아 등. 에스프레소 마티니의 핵심 재료.'},
   {name:'크림 리큐르', abv:'15–17%', desc:'베일리스 등. 유제품을 더해 부드럽고 달콤해요.'},
   {name:'견과·과일 리큐르', abv:'18–30%', desc:'아마레토(아몬드향), 미도리(멜론), 크렘 드 카시스(블랙커런트) 등 향을 강조한 리큐르.'}
 ]}
];
const CAT_EN = {'양조주':'Fermented','증류주':'Distilled','전통주':'Korean Traditional','혼성주':'Liqueur'};
const SPIRIT_BY_ID = Object.fromEntries(SPIRITS.map(s=>[s.id,s]));

/* ---------- 안주 레시피 ---------- */
const FOOD = [
{id:'french-fries', ko:'감자튀김', en:'French Fries', serves:'2인분', time:'20분', diff:1, color:'#e0a83e', pairsWith:['beer','vodka'],
 material:['감자 2개','식용유 (튀김용)','소금','파프리카 파우더(선택)'],
 steps:['감자를 껍질째 씻어 1cm 두께로 길게 썰어요.','찬물에 10분쯤 담가 전분기를 빼고 물기를 완전히 제거해요.','160℃ 기름에서 한 번 초벌 튀기고, 건져서 식혀요.','190℃로 온도를 올려 겉이 바삭해질 때까지 한 번 더 튀긴 뒤 소금을 뿌려요.'],
 note:'짭짤하고 바삭한 튀김은 맥주의 탄산·청량감과, 보드카의 깔끔한 목넘김과 잘 어울려요.'},
{id:'wings', ko:'양념 치킨윙', en:'Spicy Chicken Wings', serves:'2~3인분', time:'35분', diff:2, color:'#c23a1f', pairsWith:['beer','whisky'],
 material:['닭날개 10개','튀김가루 1컵','고추장 2큰술','케찹 2큰술','꿀 1큰술','다진 마늘 1작은술'],
 steps:['닭날개에 튀김가루를 고루 묻혀 170℃ 기름에서 노릇하게 튀겨요.','작은 팬에 고추장·케찹·꿀·다진 마늘을 넣고 약불에서 걸쭉하게 졸여 소스를 만들어요.','튀긴 닭날개를 소스에 버무려요.','통깨를 뿌려 마무리해요.'],
 note:'매콤달콤한 양념이 맥주의 청량감을 살리고, 스모키한 위스키와는 맵싸한 맛이 잘 어울려요.'},
{id:'golbaengi', ko:'골뱅이무침', en:'Golbaengi Muchim', serves:'2~3인분', time:'20분', diff:2, color:'#c94d3a', pairsWith:['soju','takju'],
 material:['골뱅이 통조림 1개','오이·당근 약간씩','양파 ½개','고춧가루 2큰술','식초·설탕 1큰술씩','소면(선택)'],
 steps:['골뱅이는 한입 크기로 썰고, 채소는 얇게 채 썰어요.','고춧가루·식초·설탕·다진 마늘로 양념장을 만들어요.','골뱅이와 채소를 양념장에 버무려요.','삶은 소면과 함께 곁들여 내요.'],
 note:'새콤달콤 매콤한 맛이 소주의 쓴맛을 깔끔하게 씻어주고, 막걸리의 단맛과도 궁합이 좋아요.'},
{id:'pajeon', ko:'김치파전', en:'Kimchi Pajeon', serves:'2~3인분', time:'25분', diff:2, color:'#d9c25a', pairsWith:['takju','yakju'],
 material:['부침가루 1컵','물 1컵','신김치 1컵(다진 것)','쪽파 한 줌','식용유'],
 steps:['부침가루와 물을 섞어 반죽을 만들어요.','다진 김치와 쪽파를 반죽에 섞어요.','달군 팬에 기름을 두르고 반죽을 얇게 펴 부쳐요.','앞뒤로 노릇하게 구워 한입 크기로 잘라요.'],
 note:'기름지고 고소한 전은 막걸리의 은은한 단맛, 청주의 깔끔함과 클래식하게 어울려요.'},
{id:'dried-snacks', ko:'육포 & 마른안주', en:'Beef Jerky Plate', serves:'2인분', time:'10분', diff:1, color:'#8a5a3a', pairsWith:['whisky','brandy'],
 material:['육포 한 줌','땅콩·아몬드 등 견과류','건포도(선택)'],
 steps:['육포를 먹기 좋은 크기로 잘라 접시에 담아요.','견과류를 곁들여요.','취향에 따라 버터나 마요네즈 소스를 곁들여도 좋아요.'],
 note:'육포의 짭짤하고 쫄깃한 감칠맛이 위스키·브랜디의 진한 풍미와 무게감 있게 어울려요.'},
{id:'nuts', ko:'허니 로스트 넛츠', en:'Honey Roasted Nuts', serves:'2~3인분', time:'15분', diff:1, color:'#b98a4a', pairsWith:['wine','whisky','brandy'],
 material:['아몬드·캐슈넛 1컵','꿀 2큰술','버터 1큰술','소금 한 꼬집'],
 steps:['팬에 버터를 녹이고 견과류를 넣어 약불에서 볶아요.','꿀을 둘러 골고루 코팅해요.','소금을 살짝 뿌려 한 김 식혀요.'],
 note:'고소하고 달콤한 견과류는 와인의 탄닌, 위스키·브랜디의 오크 풍미와 자연스럽게 어울려요.'},
{id:'cheese', ko:'치즈 플래터', en:'Cheese Platter', serves:'3~4인분', time:'10분', diff:1, color:'#e8c96a', pairsWith:['wine','brandy','whisky'],
 material:['치즈 2~3종','크래커','꿀 또는 잼','포도·무화과 등 과일'],
 steps:['치즈를 먹기 좋은 크기로 잘라요.','크래커와 과일을 곁들여 접시에 담아요.','꿀이나 잼을 곁들여 내요.'],
 note:'치즈의 짠맛·감칠맛이 와인의 산미, 브랜디·위스키의 깊은 향과 두루 잘 맞아요.'},
{id:'olives', ko:'마리네이드 올리브', en:'Marinated Olives', serves:'2~3인분', time:'10분(+숙성)', diff:1, color:'#7a8c4a', pairsWith:['gin','vodka','wine'],
 material:['올리브 1컵','올리브유 3큰술','레몬 제스트','마늘 1쪽','허브(로즈마리·타임)'],
 steps:['올리브유에 으깬 마늘과 허브를 넣고 약불에서 향을 우려요.','올리브와 레몬 제스트를 넣어 버무려요.','냉장고에서 30분 이상 재워 향이 배게 해요.'],
 note:'올리브의 짭짤한 감칠맛이 진의 주니퍼 향, 보드카의 깔끔함과 산뜻하게 어울려요.'},
{id:'nachos', ko:'나초 & 살사', en:'Nachos & Salsa', serves:'2~3인분', time:'20분', diff:2, color:'#d99a3a', pairsWith:['tequila','beer'],
 material:['나초칩 한 봉지','토마토 2개','양파 ¼개','라임즙','슈레드 치즈','할라피뇨(선택)'],
 steps:['토마토·양파를 잘게 다져 라임즙·소금으로 살사를 만들어요.','나초칩 위에 치즈를 듬뿍 올려 오븐에서 녹여요.','살사와 할라피뇨를 올려 내요.'],
 note:'짭짤하고 매콤한 멕시칸 안주는 테킬라와 클래식한 짝이고, 맥주와도 잘 어울려요.'},
{id:'steak', ko:'스테이크', en:'Grilled Steak', serves:'2인분', time:'25분', diff:2, color:'#8a3a2a', pairsWith:['wine','whisky','brandy'],
 material:['스테이크용 고기 200g','소금·후추','버터 1큰술','마늘 2쪽','로즈마리(선택)'],
 steps:['고기를 실온에 20분쯤 꺼내두고 소금·후추로 간해요.','달군 팬에 센 불로 양면을 짧게 구워 겉면을 익혀요.','버터·마늘·로즈마리를 넣고 불을 줄여 속까지 익혀요.','5분쯤 레스팅 후 썰어 내요.'],
 note:'묵직한 육즙과 풍미는 레드 와인의 탄닌, 위스키·브랜디의 깊은 향과 잘 어우러져요.'},
{id:'shrimp', ko:'갈릭 버터 새우', en:'Garlic Butter Shrimp', serves:'2인분', time:'15분', diff:2, color:'#d97a5a', pairsWith:['vodka','wine','liqueur'],
 material:['새우 12마리','버터 2큰술','다진 마늘 3쪽','레몬즙','파슬리'],
 steps:['새우는 껍질을 벗기고 내장을 제거해요.','팬에 버터를 녹이고 다진 마늘을 볶아 향을 내요.','새우를 넣고 속까지 익도록 볶아요.','레몬즙과 파슬리를 뿌려 마무리해요.'],
 note:'버터와 마늘의 고소한 향이 보드카의 깔끔함, 화이트 와인의 산미와 잘 어울려요.'},
{id:'dubukimchi', ko:'두부김치', en:'Dubu Kimchi', serves:'2~3인분', time:'25분', diff:2, color:'#c94a3a', pairsWith:['soju','takju'],
 material:['두부 1모','신김치 1컵','돼지고기(선택) 100g','참기름·설탕'],
 steps:['두부는 통째로 데쳐 먹기 좋게 썰어요.','팬에 김치와 돼지고기를 볶아요. 설탕과 참기름으로 간을 맞춰요.','볶은 김치를 두부 옆에 곁들여 내요.'],
 note:'익힌 두부의 담백함과 볶음김치의 매콤함이 소주·막걸리의 목넘김과 잘 맞아요.'},
{id:'jokbal', ko:'족발 플레이트', en:'Jokbal Plate', serves:'2~3인분', time:'15분(완제품 활용)', diff:1, color:'#c9926a', pairsWith:['soju'],
 material:['시판 족발 1팩','쌈장·마늘·쪽파','상추·깻잎'],
 steps:['족발을 먹기 좋게 슬라이스해요.','쌈채소·마늘·쪽파와 함께 접시에 담아요.','쌈장을 곁들여 내요.'],
 note:'쫄깃하고 기름진 족발은 소주의 깔끔한 목넘김과 클래식하게 어울려요.'},
{id:'salmon', ko:'훈제연어 카나페', en:'Smoked Salmon Canapé', serves:'2인분', time:'15분', diff:1, color:'#e0836a', pairsWith:['wine','vodka','gin'],
 material:['훈제연어 100g','바게트 슬라이스','크림치즈','딜(또는 파슬리)','케이퍼(선택)'],
 steps:['바게트에 크림치즈를 발라요.','훈제연어를 올려요.','딜과 케이퍼로 장식해요.'],
 note:'훈제연어의 스모키하고 짭짤한 풍미가 스파클링 와인, 보드카·진의 깔끔함과 잘 어울려요.'},
{id:'chocolate', ko:'다크초콜릿 & 베리', en:'Dark Chocolate & Berries', serves:'2인분', time:'10분', diff:1, color:'#4a2e22', pairsWith:['liqueur','wine','brandy'],
 material:['다크초콜릿 100g','딸기·블루베리 등 베리류','견과류(선택)'],
 steps:['초콜릿을 한입 크기로 잘라요.','베리류를 씻어 물기를 제거해요.','접시에 초콜릿과 베리를 함께 담아요.'],
 note:'다크초콜릿의 쌉쌀함이 혼성주의 단맛, 포트와인·브랜디의 진한 풍미와 디저트처럼 잘 어울려요.'},
{id:'rolled-omelette', ko:'계란말이', en:'Rolled Omelette', serves:'2~3인분', time:'15분', diff:2, color:'#f2c94c', pairsWith:['soju','takju'],
 material:['달걀 4개','쪽파 2대','당근 약간','소금 약간','식용유'],
 steps:['달걀을 풀고 잘게 다진 쪽파·당근과 소금을 넣어 섞어요.','약불로 달군 팬에 기름을 얇게 두르고 달걀물을 ⅓만 부어요.','반쯤 익으면 한쪽 끝부터 돌돌 말고, 남은 달걀물을 조금씩 부어 이어서 말아요.','한 김 식힌 뒤 도톰하게 썰어 내요.'],
 note:'부드럽고 담백한 맛이 소주의 쓴맛을 순하게 받쳐주고, 막걸리와도 편안하게 어울려요.'},
{id:'fishcake-soup', ko:'어묵탕', en:'Fish Cake Soup', serves:'2~3인분', time:'25분', diff:1, color:'#e8c07a', pairsWith:['soju','yakju'],
 material:['모둠 어묵 300g','무 ¼개','다시마 1장','국간장 1큰술','대파·청양고추 약간'],
 steps:['물 1L에 다시마와 도톰하게 썬 무를 넣고 15분쯤 끓여 육수를 내요.','다시마를 건지고 국간장으로 간을 맞춰요.','꼬치에 꿴 어묵을 넣고 5분쯤 더 끓여요.','대파와 청양고추를 올려 내요.'],
 note:'뜨끈하고 시원한 국물이 소주와 짝을 이루는 대표 안주예요. 은은한 단맛의 약주와도 잘 어울려요.'},
{id:'butter-squid', ko:'오징어 버터구이', en:'Butter Grilled Squid', serves:'2인분', time:'15분', diff:1, color:'#e0b07a', pairsWith:['beer','soju'],
 material:['손질한 오징어 1마리','버터 1큰술','간장 1큰술','설탕 ½큰술','마요네즈·청양고추(찍어 먹기용)'],
 steps:['오징어 몸통에 칼집을 넣고 먹기 좋게 썰어요.','달군 팬에 버터를 녹이고 오징어를 센 불에 빠르게 볶아요.','간장과 설탕을 넣고 윤기 나게 한 번 더 볶아요.','다진 청양고추를 넣은 마요네즈를 곁들여 내요.'],
 note:'버터의 고소함과 짭짤한 간장 맛이 맥주를 부르고, 소주 안주로도 손색없어요.'},
{id:'dried-pollock', ko:'먹태구이', en:'Grilled Dried Pollock', serves:'2인분', time:'10분', diff:1, color:'#c9a877', pairsWith:['beer','soju'],
 material:['먹태 1마리','마요네즈 3큰술','간장 1큰술','청양고추 1개','설탕 약간'],
 steps:['먹태에 물을 살짝 뿌려 부드럽게 한 뒤 약불에서 앞뒤로 노릇하게 구워요.','먹기 좋게 찢고 가시를 골라내요.','마요네즈에 간장, 다진 청양고추, 설탕을 섞어 소스를 만들어요.','구운 먹태를 소스에 찍어 먹어요.'],
 note:'쫄깃하게 씹히는 맛과 매콤한 청양마요가 맥주의 청량감과 잘 어울려요. 소주에도 곁들이기 좋아요.'},
{id:'caprese', ko:'카프레제', en:'Caprese', serves:'2인분', time:'10분', diff:1, color:'#d9463a', pairsWith:['wine','gin'],
 material:['토마토 2개','생 모차렐라 125g','바질 잎 한 줌','엑스트라 버진 올리브유','소금·후추','발사믹 글레이즈(선택)'],
 steps:['토마토와 모차렐라를 비슷한 두께로 둥글게 썰어요.','접시에 토마토, 모차렐라, 바질 잎을 번갈아 겹쳐 담아요.','소금과 후추를 뿌리고 올리브유를 둘러요.','취향에 따라 발사믹 글레이즈를 조금 뿌려요.'],
 note:'신선한 토마토와 부드러운 치즈가 산미 있는 화이트 와인과 잘 맞고, 바질 향이 진 토닉 같은 진 칵테일과도 어울려요.'},
{id:'bruschetta', ko:'브루스케타', en:'Bruschetta', serves:'2~3인분', time:'15분', diff:1, color:'#c94a3a', pairsWith:['wine','beer'],
 material:['바게트 ½개','방울토마토 10개','마늘 1쪽','바질 잎 약간','올리브유 2큰술','소금·후추'],
 steps:['방울토마토를 잘게 썰어 다진 바질, 올리브유, 소금, 후추와 섞어요.','바게트를 1cm 두께로 썰어 오븐이나 팬에 바삭하게 구워요.','구운 빵 단면에 마늘을 문질러 향을 입혀요.','토마토 토핑을 올려 바로 내요.'],
 note:'바삭한 빵과 상큼한 토마토가 와인 한 잔과 가볍게 어울리고, 맥주 안주로도 좋아요.'},
{id:'prosciutto-melon', ko:'프로슈토 멜론', en:'Prosciutto & Melon', serves:'2~3인분', time:'10분', diff:1, color:'#f0a868', pairsWith:['wine','gin'],
 material:['멜론 ¼통','프로슈토 6~8장','후추 약간','올리브유(선택)'],
 steps:['멜론 껍질과 씨를 제거하고 길쭉하게 썰어요.','멜론 조각을 프로슈토로 한 번씩 감싸요.','후추를 살짝 뿌리고 취향에 따라 올리브유를 둘러요.'],
 note:'달콤한 멜론과 짭짤한 햄의 대비가 화이트·스파클링 와인과 잘 어울리고, 진의 허브 향과도 잘 맞아요.'},
{id:'guacamole', ko:'과카몰리', en:'Guacamole', serves:'3~4인분', time:'15분', diff:1, color:'#8fae4a', pairsWith:['tequila','beer'],
 material:['잘 익은 아보카도 2개','양파 ¼개','토마토 ½개','라임 1개','고수(선택)','소금','나초칩'],
 steps:['아보카도를 반으로 갈라 씨를 빼고 과육을 포크로 으깨요.','잘게 다진 양파, 토마토, 고수를 넣어요.','라임즙과 소금으로 간을 맞춰 섞어요.','나초칩과 함께 내요.'],
 note:'라임과 아보카도의 산뜻하고 고소한 맛이 테킬라와 전통적인 짝이에요. 맥주와도 잘 어울려요.'},
{id:'karaage', ko:'가라아게', en:'Karaage', serves:'2~3인분', time:'40분', diff:2, color:'#d99a3a', pairsWith:['beer','whisky'],
 material:['닭다리살 400g','간장 2큰술','청주 1큰술','다진 생강·마늘 1작은술씩','감자전분 ½컵','식용유 (튀김용)','레몬 조각'],
 steps:['닭다리살을 한입 크기로 썰어 간장, 청주, 생강, 마늘에 20분쯤 재워요.','재운 닭에 감자전분을 고루 묻혀요.','170℃ 기름에서 4분쯤 튀기고 건져 잠시 두었다가, 한 번 더 짧게 튀겨요.','레몬 조각을 곁들여 내요.'],
 note:'바삭한 일본식 닭튀김은 맥주는 물론 위스키 하이볼과 특히 잘 어울려요.'},
{id:'edamame', ko:'에다마메', en:'Salted Edamame', serves:'2~3인분', time:'10분', diff:1, color:'#7cae4a', pairsWith:['beer','yakju'],
 material:['냉동 풋콩(에다마메) 300g','굵은소금 1큰술'],
 steps:['끓는 물에 소금을 조금 넣고 풋콩을 4~5분 삶아요.','체에 밭쳐 물기를 빼요.','뜨거울 때 굵은소금을 고루 뿌려요.'],
 note:'짭짤하고 고소한 풋콩은 맥주 안주의 기본이에요. 담백한 맛이라 청주·약주와도 잘 어울려요.'},
{id:'sausage-stir-fry', ko:'소시지 야채볶음', en:'Sausage Stir-fry', serves:'2~3인분', time:'15분', diff:1, color:'#c9503a', pairsWith:['beer','soju'],
 material:['비엔나소시지 20개','양파 ½개','파프리카 ½개','케첩 3큰술','굴소스 ½큰술','올리고당 1큰술'],
 steps:['소시지에 칼집을 넣고 끓는 물에 살짝 데쳐요.','양파와 파프리카를 한입 크기로 썰어요.','팬에 기름을 두르고 소시지와 채소를 볶아요.','케첩, 굴소스, 올리고당을 넣고 윤기 나게 볶아요.'],
 note:'달콤짭짤한 소스가 맥주와 소주 모두와 편하게 어울리는 친숙한 안주예요.'},
{id:'tteokbokki', ko:'떡볶이', en:'Tteokbokki', serves:'2인분', time:'20분', diff:1, color:'#d4332a', pairsWith:['soju','beer'],
 material:['떡볶이 떡 300g','어묵 2장','대파 1대','고추장 2큰술','고춧가루 1큰술','설탕 1큰술','간장 1큰술'],
 steps:['물 400ml에 고추장, 고춧가루, 설탕, 간장을 풀어 끓여요.','떡을 넣고 중불에서 저어가며 끓여요.','어묵과 대파를 넣고 소스가 걸쭉해질 때까지 졸여요.'],
 note:'매콤달콤한 떡볶이는 소주와 잘 맞고, 맥주로 매운맛을 식히기에도 좋아요.'},
{id:'acorn-jelly', ko:'도토리묵무침', en:'Acorn Jelly Salad', serves:'2~3인분', time:'15분', diff:1, color:'#7a5a3a', pairsWith:['takju','yakju'],
 material:['도토리묵 1모','상추·오이 약간','쑥갓(선택)','간장 2큰술','고춧가루 1큰술','다진 마늘·참기름·깨 약간'],
 steps:['도토리묵을 한입 크기로 썰어요.','채소는 먹기 좋게 썰어요.','간장, 고춧가루, 다진 마늘, 참기름, 깨로 양념장을 만들어요.','묵과 채소를 양념장에 살살 버무려요.'],
 note:'담백하고 탱글한 묵과 고소한 양념이 막걸리와 잘 어울리는 전통 안주예요.'},
{id:'beef-jeon', ko:'육전', en:'Beef Jeon', serves:'2~3인분', time:'20분', diff:2, color:'#d9a24a', pairsWith:['yakju','takju'],
 material:['육전용 소고기(홍두깨살) 300g','달걀 2개','부침가루 ½컵','소금·후추','식용유','부추 겉절이(선택)'],
 steps:['얇게 썬 소고기의 핏물을 키친타월로 닦고 소금·후추로 밑간해요.','고기에 부침가루를 얇게 묻혀요.','달걀물을 입혀 기름 두른 팬에 앞뒤로 노릇하게 부쳐요.','부추 겉절이를 곁들여 내요.'],
 note:'고소한 고기전은 은은한 단맛의 약주와 잘 어울리고, 막걸리와도 좋은 짝이에요.'},
{id:'potato-pancake', ko:'감자전', en:'Potato Pancake', serves:'2인분', time:'25분', diff:2, color:'#e0c07a', pairsWith:['takju','yakju'],
 material:['감자 3개','소금 약간','부침가루 2큰술(선택)','청양고추 1개','식용유'],
 steps:['감자 껍질을 벗겨 강판에 곱게 갈아요.','체에 밭쳐 물기를 빼고, 가라앉은 전분은 다시 섞어요.','소금으로 간하고 다진 청양고추를 넣어요.','기름을 넉넉히 두른 팬에 얇게 펴서 앞뒤로 바삭하게 부쳐요.'],
 note:'겉은 바삭하고 속은 쫀득한 감자전은 막걸리와 잘 어울리는 대표 안주예요.'},
{id:'suyuk', ko:'수육', en:'Boiled Pork Slices', serves:'3~4인분', time:'1시간', diff:2, color:'#d9b8a0', pairsWith:['soju','yakju'],
 material:['통삼겹살 또는 앞다리살 600g','된장 1큰술','대파 1대','마늘 5쪽','통후추 약간','새우젓·김치(곁들임)'],
 steps:['냄비에 물을 붓고 된장, 대파, 마늘, 통후추를 넣어 끓여요.','고기를 넣고 뚜껑을 덮어 중약불에서 50분쯤 삶아요.','젓가락으로 찔러 핏물이 나오지 않으면 건져 한 김 식혀요.','얇게 썰어 새우젓과 김치를 곁들여 내요.'],
 note:'부드러운 수육은 깔끔한 소주, 향긋한 약주와 모두 잘 어울려요.'},
{id:'octopus', ko:'문어숙회', en:'Blanched Octopus', serves:'2~3인분', time:'20분', diff:2, color:'#c96a6a', pairsWith:['soju','yakju'],
 material:['손질한 생문어 다리 2개','굵은소금','초고추장 또는 기름장','오이(선택)'],
 steps:['생문어는 굵은소금으로 주물러 씻어 점액을 없애요.','끓는 물에 문어를 넣었다 뺐다 몇 번 반복한 뒤 다리 굵기에 따라 3~5분쯤 데쳐요.','찬물에 헹궈 식히고 얇게 썰어요.','초고추장이나 기름장을 곁들여 내요.'],
 note:'쫄깃하고 담백한 문어는 소주와 잘 어울리고, 깔끔한 약주와도 좋은 짝이에요.'},
{id:'fruit-platter', ko:'과일 플래터', en:'Fruit Platter', serves:'3~4인분', time:'15분', diff:1, color:'#e05a6a', pairsWith:['liqueur','wine','rum'],
 material:['제철 과일 3~4가지(딸기·포도·오렌지·키위 등)','민트 잎(선택)'],
 steps:['과일을 씻어 물기를 닦아요.','먹기 좋은 크기로 썰고 오렌지는 껍질을 벗겨 조각내요.','색이 겹치지 않게 접시에 담고 민트 잎으로 장식해요.'],
 note:'상큼하고 달콤한 과일은 리큐르나 와인, 럼 칵테일처럼 단맛 있는 술과 가볍게 어울려요.'},
{id:'affogato', ko:'아포가토', en:'Affogato', serves:'1인분', time:'5분', diff:1, color:'#6b3a1e', pairsWith:['liqueur','rum','brandy'],
 material:['바닐라 아이스크림 2스쿱','에스프레소 1샷(30ml)','커피 리큐르 또는 브랜디 1큰술(선택)'],
 steps:['차갑게 둔 그릇에 바닐라 아이스크림을 담아요.','갓 추출한 뜨거운 에스프레소를 부어요.','취향에 따라 커피 리큐르나 브랜디를 조금 더해 바로 먹어요.'],
 note:'달콤쌉쌀한 디저트라 커피 리큐르, 다크 럼, 브랜디 같은 식후주와 잘 어울려요.'},
{id:'smoked-duck', ko:'훈제오리 부추무침', en:'Smoked Duck & Chives', serves:'2~3인분', time:'15분', diff:1, color:'#b0603a', pairsWith:['soju','whisky'],
 material:['훈제오리 300g','부추 한 줌','양파 ¼개','간장·식초·설탕 1큰술씩','고춧가루 ½큰술','참기름 약간'],
 steps:['훈제오리를 기름 없는 팬에 앞뒤로 노릇하게 구워 기름을 빼요.','부추는 5cm 길이로 썰고 양파는 얇게 채 썰어요.','간장, 식초, 설탕, 고춧가루, 참기름으로 양념을 만들어 채소를 버무려요.','구운 오리와 부추무침을 함께 담아 내요.'],
 note:'훈연 향이 나는 오리는 소주와 잘 맞고, 스모키한 위스키와도 향이 잘 어우러져요.'},
{id:'fish-tacos', ko:'피시 타코', en:'Fish Tacos', serves:'2인분', time:'30분', diff:2, color:'#e8c06a', pairsWith:['tequila','beer','rum'],
 material:['흰살생선(대구 등) 200g','또르티야 4장','튀김가루 ½컵','양배추 채 한 줌','라임 1개','사워크림 또는 마요네즈','칠리 파우더 약간'],
 steps:['생선을 한입 크기로 썰어 소금·칠리 파우더로 밑간해요.','튀김가루 반죽을 입혀 170℃ 기름에 바삭하게 튀겨요.','데운 또르티야에 양배추 채와 생선을 올려요.','사워크림을 뿌리고 라임즙을 짜서 내요.'],
 note:'바삭한 생선과 라임의 산미가 테킬라와 잘 어울리고, 라거 맥주나 럼 칵테일과도 좋아요.'},
{id:'ceviche', ko:'세비체', en:'Ceviche', serves:'2인분', time:'25분', diff:2, color:'#f0e0a0', pairsWith:['tequila','gin','vodka'],
 material:['횟감용 흰살생선 또는 새우 200g','라임 3개','적양파 ¼개','토마토 ½개','고수 약간','소금','할라피뇨(선택)'],
 steps:['횟감용 생선을 1cm 크기로 깍둑 썰어요.','라임즙을 넉넉히 부어 냉장고에서 15분쯤 두면 겉면이 하얗게 변해요.','잘게 다진 적양파, 토마토, 고수, 할라피뇨를 넣고 소금으로 간해요.','차갑게 해서 바로 내요.'],
 note:'라임에 절인 해산물의 산뜻한 맛이 테킬라, 진, 보드카 같은 깔끔한 증류주와 잘 어울려요.'},
{id:'stuffed-mushrooms', ko:'양송이 치즈구이', en:'Cheesy Stuffed Mushrooms', serves:'2~3인분', time:'20분', diff:1, color:'#d9c09a', pairsWith:['wine','beer'],
 material:['양송이버섯 10개','베이컨 2줄','양파 약간','모차렐라 치즈 ½컵','파슬리 가루'],
 steps:['양송이 기둥을 떼어 내고 기둥은 잘게 다져요.','다진 기둥, 베이컨, 양파를 팬에 볶아 속을 만들어요.','버섯 갓에 속을 채우고 모차렐라 치즈를 올려요.','200℃ 오븐이나 에어프라이어에서 10분쯤 치즈가 녹을 때까지 구워요.'],
 note:'고소한 치즈와 버섯의 감칠맛이 레드 와인, 맥주와 잘 어울려요.'},
{id:'gizzards', ko:'닭똥집 볶음', en:'Stir-fried Chicken Gizzards', serves:'2~3인분', time:'20분', diff:2, color:'#b8703a', pairsWith:['soju','beer'],
 material:['닭모래집(닭똥집) 400g','마늘 10쪽','청양고추 2개','소금·후추','식용유','참기름 약간'],
 steps:['닭모래집의 흰 막을 떼어 내고 한입 크기로 썰어요.','물에 헹궈 잡내를 빼고 물기를 닦아요.','팬에 기름을 두르고 편 썬 마늘을 볶다가 모래집을 넣어 센 불에 볶아요.','청양고추를 넣고 소금·후추로 간한 뒤 참기름을 둘러요.'],
 note:'꼬들꼬들 씹히는 식감과 마늘 향이 소주와 잘 맞는 포장마차 대표 안주예요. 맥주와도 좋아요.'},
{id:'garlic-bread', ko:'마늘빵', en:'Garlic Bread', serves:'2~3인분', time:'15분', diff:1, color:'#e8c47a', pairsWith:['wine','beer'],
 material:['바게트 ½개','버터 50g(실온)','다진 마늘 1큰술','설탕 1큰술','파슬리 가루'],
 steps:['실온 버터에 다진 마늘, 설탕, 파슬리를 섞어요.','바게트를 2cm 두께로 썰어 한 면에 마늘 버터를 발라요.','180℃ 오븐이나 에어프라이어에서 7~8분 노릇하게 구워요.'],
 note:'고소한 마늘 버터 향이 와인, 맥주와 두루 잘 어울리는 안주예요.'}
];
const FOOD_BY_ID = Object.fromEntries(FOOD.map(f=>[f.id,f]));

/* ---------- 홈파티 아이디어 ----------
   파티 종류마다 어울리는 술 · 칵테일(drinks: RECIPES id), 술 상식(spirits: SPIRITS id), 안주(foods: FOOD id),
   필요한 것(items: 묶음별 목록), 준비 순서(prep: [언제, 할 일])를 적어요. 없는 id를 쓰면 빌드가 멈춰요. */
const PARTIES = [
{id:'wine-cheese', ko:'와인 & 치즈 나이트', en:'Wine & Cheese Night', people:'2~4명', time:'저녁 · 2~3시간', mood:['차분한', '대화 중심'],
 summary:'와인 두 병과 치즈 몇 가지로 길게 이야기하는 저녁이에요. 요리 부담이 적어 처음 여는 홈파티로도 좋아요.',
 drinks:['kir', 'aperol-spritz', 'mimosa'], spirits:['wine'],
 foods:['cheese', 'olives', 'prosciutto-melon', 'bruschetta', 'chocolate', 'garlic-bread'],
 items:[
  ['잔 · 도구', ['와인잔 (인원 수 + 여유 2개)', '코르크 스크루', '와인 쿨러 또는 얼음 버킷', '치즈 나이프와 도마']],
  ['장보기', ['레드 와인 1병 · 화이트 또는 스파클링 1병 (4명 기준)', '치즈 3가지: 단단한 것 · 부드러운 것 · 블루', '크래커와 바게트', '물 넉넉히']],
  ['테이블', ['작은 앞접시와 냅킨', '은은한 조명이나 캔들', '와인 이름을 적을 메모지']]],
 prep:[['전날', '화이트 · 스파클링 와인을 냉장고에 넣어 둬요.'], ['1시간 전', '치즈를 냉장고에서 꺼내 실온에 둬요. 향과 맛이 살아나요.'], ['30분 전', '레드 와인을 열어 두고, 바게트를 썰어 구워요.'], ['시작', '가벼운 와인과 치즈부터, 진한 와인과 블루치즈는 나중에 내요.']]},

{id:'birthday', ko:'생일 파티', en:'Birthday Party', people:'6~10명', time:'저녁 · 3시간 이상', mood:['신나는', '사진 찍기 좋은'],
 summary:'인원이 많은 날은 한 잔씩 만드는 칵테일보다 미리 만들어 두는 펀치와 손으로 집어 먹는 안주가 편해요. 술을 안 마시는 손님을 위한 무알콜 한 가지는 꼭 준비해요.',
 drinks:['tequila-sunrise', 'cosmopolitan', 'mimosa', 'virgin-fruit-punch', 'shirley-temple'], spirits:[],
 foods:['wings', 'nachos', 'karaage', 'french-fries', 'fruit-platter'],
 items:[
  ['잔 · 도구', ['하이볼 글라스 또는 튼튼한 컵 (인원 × 2)', '펀치를 담을 큰 볼이나 피처', '지거와 바 스푼', '얼음 넉넉히 (1명당 약 0.5kg)']],
  ['장보기', ['케이크와 초 · 라이터', '무알콜 음료 (주스 · 진저에일 · 탄산수)', '일회용 접시 · 포크 · 냅킨']],
  ['테이블 · 분위기', ['풍선이나 가랜드', '사진 찍을 벽 한쪽', '플레이리스트']]],
 prep:[['3일 전', '케이크를 예약하고 손님 수를 확인해요.'], ['전날', '얼음을 사거나 얼려 두고, 음료를 냉장고에 넣어요.'], ['3시간 전', '튀김류 밑준비, 과일 플래터를 만들어 랩을 씌워 둬요.'], ['1시간 전', '펀치를 큰 볼에 만들어 두고, 얼음은 마시기 직전에 넣어요.']]},

{id:'holiday', ko:'연말 · 크리스마스 홈파티', en:'Holiday Party', people:'4~8명', time:'저녁 · 3~4시간', mood:['따뜻한', '조금 차려입은'],
 summary:'한 해를 마무리하는 자리라 평소보다 조금 힘을 줘도 좋아요. 메인 요리 하나와 칵테일 두세 가지, 디저트 칵테일로 마무리해요.',
 drinks:['moscow-mule', 'cosmopolitan', 'espresso-martini', 'brandy-alexander'], spirits:['brandy'],
 foods:['steak', 'salmon', 'caprese', 'stuffed-mushrooms', 'chocolate'],
 items:[
  ['잔 · 도구', ['칵테일 셰이커와 지거', '쿠페 또는 칵테일 글라스', '코퍼 머그 (모스코 뮬용, 없으면 하이볼 글라스)']],
  ['장보기', ['크랜베리 · 로즈마리 같은 빨강 · 초록 가니시', '에스프레소 (모카포트나 캡슐)', '디저트용 다크초콜릿']],
  ['테이블 · 분위기', ['캔들과 작은 조명', '테이블보 한 장', '연말 플레이리스트']]],
 prep:[['전날', '스테이크 고기를 사서 소금을 해 두고, 에스프레소 마티니용 커피를 내려 식혀 둬요.'], ['2시간 전', '카프레제 · 양송이 치즈구이 재료를 손질해요.'], ['30분 전', '잔을 냉동실에 넣어 차갑게 해요.'], ['시작', '모스코 뮬로 시작해 메인을 먹고, 브랜디 알렉산더나 에스프레소 마티니로 마무리해요.']]},

{id:'housewarming', ko:'집들이', en:'Housewarming', people:'6~10명', time:'저녁 · 3시간', mood:['푸짐한', '편안한'],
 summary:'한식 안주를 크게 한 상 차리고, 소주 · 맥주 · 막걸리를 기본으로 두는 자리예요. 우리술 칵테일 하나를 곁들이면 이야깃거리가 돼요.',
 drinks:['gochang', 'geumsan'], spirits:['soju', 'beer', 'takju'],
 foods:['suyuk', 'pajeon', 'tteokbokki', 'dubukimchi', 'beef-jeon'],
 items:[
  ['잔 · 도구', ['소주잔 · 맥주잔 넉넉히', '막걸리 잔이나 사발', '병따개 두 개 (한 개는 꼭 없어져요)']],
  ['장보기', ['소주 · 맥주 · 막걸리', '쌈 채소와 김치', '얼음과 생수']],
  ['테이블', ['큰 접시와 앞접시 · 수저 넉넉히', '분리수거 봉투', '선물로 받은 술을 둘 자리']]],
 prep:[['전날', '수육 양념을 준비하고, 전 반죽 재료를 손질해요.'], ['3시간 전', '수육을 삶기 시작해요.'], ['1시간 전', '전을 부치고, 떡볶이는 손님이 오면 바로 데워 내요.'], ['시작', '도착한 순서대로 맥주 한 잔, 다 모이면 우리술 칵테일로 건배해요.']]},

{id:'game-night', ko:'영화 · 게임 나이트', en:'Movie & Game Night', people:'3~6명', time:'밤 · 3시간 이상', mood:['느긋한', '편한 옷차림'],
 summary:'화면이나 게임판에 집중하는 날이라 한 손으로 들고 마실 수 있는 하이볼과, 흘려도 괜찮은 안주가 좋아요.',
 drinks:['gin-tonic', 'cuba-libre', 'moscow-mule', 'arnold-palmer'], spirits:['gin', 'rum'],
 foods:['nachos', 'french-fries', 'butter-squid', 'dried-snacks', 'edamame', 'sausage-stir-fry'],
 items:[
  ['잔 · 도구', ['하이볼 글라스', '얼음 넉넉히', '코스터 (테이블 물자국 방지)']],
  ['장보기', ['토닉워터 · 콜라 · 진저비어', '라임', '나눠 먹을 큰 볼']],
  ['테이블 · 분위기', ['물티슈', '보드게임이나 영화 목록', '담요와 쿠션']]],
 prep:[['전날', '토닉워터와 콜라를 냉장고에 넣어 둬요. 차가워야 탄산이 오래가요.'], ['1시간 전', '라임을 웨지로 썰어 두고, 마른안주를 그릇에 덜어요.'], ['시작', '하이볼은 진 · 럼만 정해 두면 손님이 직접 만들어 마실 수 있어요.']]},

{id:'anniversary', ko:'기념일 디너', en:'Anniversary Dinner', people:'2~4명', time:'저녁 · 2~3시간', mood:['차분한', '분위기 있는'],
 summary:'둘이나 가까운 몇 명이 조용히 축하하는 저녁이에요. 메인 요리 하나와 스파클링 와인, 가벼운 칵테일이면 충분해요. 꽃과 캔들이 분위기를 만들어요.',
 drinks:['aperol-spritz', 'cosmopolitan', 'virgin-mojito'], spirits:['wine'],
 foods:['steak', 'caprese', 'salmon', 'cheese', 'chocolate'],
 items:[
  ['잔 · 도구', ['플루트 또는 와인잔', '칵테일 셰이커와 지거', '스테이크 나이프']],
  ['장보기', ['스파클링 와인 1병', '스테이크용 고기', '디저트 (다크초콜릿 · 베리)']],
  ['테이블 · 분위기', ['꽃 한 다발', '캔들 두 개', '조용한 플레이리스트']]],
 prep:[['전날', '스파클링 와인을 냉장고에 넣고, 고기에 소금을 해 둬요.'], ['1시간 전', '카프레제와 연어 카나페를 만들어 냉장고에 둬요.'], ['30분 전', '고기를 실온에 꺼내 두고 잔을 차갑게 해요.'], ['시작', '스파클링으로 건배하고, 스테이크는 앉은 뒤에 구워 바로 내요.']]},

{id:'family', ko:'가족 모임', en:'Family Gathering', people:'4~8명', time:'점심 또는 저녁 · 2~3시간', mood:['푸짐한', '편안한'],
 summary:'어른부터 아이까지 함께하는 자리라 무알코올 음료를 넉넉히 두고, 함께 집어 먹는 한식 안주를 크게 차려요. 술은 막걸리 · 맥주 정도로 가볍게요.',
 drinks:['arnold-palmer', 'cinderella', 'fresh-lemon-squash'], spirits:['takju', 'beer'],
 foods:['suyuk', 'beef-jeon', 'potato-pancake', 'rolled-omelette', 'fruit-platter'],
 items:[
  ['잔 · 도구', ['물잔 · 주스잔 넉넉히', '큰 피처 (무알코올 음료용)', '막걸리 잔']],
  ['장보기', ['막걸리 · 맥주 조금', '무알코올 음료 재료 (레몬 · 홍차 · 주스)', '과일']],
  ['테이블', ['큰 접시와 앞접시', '아이용 컵과 수저', '물티슈']]],
 prep:[['전날', '수육 고기와 전 재료를 사 두고, 홍차를 우려 차갑게 식혀요.'], ['2시간 전', '수육을 삶기 시작해요.'], ['1시간 전', '감자전 · 육전을 부치고 계란말이를 만들어요.'], ['시작', '무알코올 음료는 큰 피처에 미리 만들어 두면 누구나 따라 마실 수 있어요.']]},

{id:'brunch', ko:'브런치 파티', en:'Brunch Party', people:'4~6명', time:'낮 · 11시~2시', mood:['밝은', '가벼운'],
 summary:'낮에 모이는 자리라 도수가 낮은 칵테일과 무알콜 음료를 넉넉히 준비해요. 달걀 요리와 과일만 있어도 상이 차요.',
 drinks:['mimosa', 'bloody-mary', 'aperol-spritz', 'virgin-mary', 'fresh-lemon-squash'], spirits:[],
 foods:['rolled-omelette', 'fruit-platter', 'salmon', 'caprese', 'bruschetta'],
 items:[
  ['잔 · 도구', ['플루트 글라스 (미모사용)', '큰 피처 (레몬 스쿼시 · 블러디 메리)', '커피 도구']],
  ['장보기', ['스파클링 와인과 착즙 오렌지주스', '토마토 주스 · 레몬', '바게트와 버터']],
  ['테이블 · 분위기', ['꽃 한 다발', '밝은 테이블보', '햇빛이 드는 자리']]],
 prep:[['전날', '스파클링 와인과 오렌지주스를 차갑게 해 두고, 과일을 사 둬요.'], ['1시간 전', '계란말이를 만들고 연어 카나페를 올려요.'], ['시작', '미모사는 마시기 직전에 잔에서 바로 섞어요.']]}
];

return {C, GLASS, BASES, BASE_EN, FLAVORS, DIFF, RECIPES, BY_ID, EXAM, EXAM_SOURCE, examAmount, CATS, CAT_EN, SPIRITS, SPIRIT_BY_ID, FOOD, FOOD_BY_ID, ALIAS, PARTIES};
})();
